"use client";

import { FormEvent, useCallback, useEffect, useState, type ReactNode } from "react";
import { Calculator, Plus, RefreshCcw, Route as RouteIcon, Truck } from "lucide-react";
import { PermissionGuard } from "@/components/permissions/permission-guard";
import { OperationPageHeader } from "@/components/ui/operation-page-header";
import { OperationMetrics, OperationToolbar } from "@/components/ui/operation-primitives";
import { OperationButton, OperationField, OperationFilterPopover, OperationMetric, OperationMetricGrid } from "@/components/ui/operation-controls";
import { OperationDrawer } from "@/components/ui/operation-drawer";
import { FormGeographyFields } from "@/components/ui/geography-fields";
import { LoadingState } from "@/components/ui/page-state";
import { addPrice, catalog, createRoute, createService, simulate, type Route, type Service } from "@/services/route-catalog";

const button = "inline-flex h-8 items-center justify-center gap-1.5 rounded-[5px] border border-[#d6dadd] bg-white px-3 text-[12px] font-medium hover:bg-[#f5f6f6]";
const primary = "inline-flex h-8 items-center justify-center gap-1.5 rounded-[5px] bg-[#16855f] px-3 text-[12px] font-semibold text-white hover:bg-[#126f50]";
const input = "h-9 w-full rounded-[5px] border border-[#d6dadd] bg-white px-3 text-[13px] outline-none focus:border-[#16855f]";
type Action = "route" | "service" | "price" | "simulate";

export function RouteCatalogPage() {
  const [routes, setRoutes] = useState<Route[]>([]);
  const [services, setServices] = useState<Service[]>([]);
  const [action, setAction] = useState<Action | null>(null);
  const [view, setView] = useState<"routes" | "services">("routes");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const data = await catalog(); setRoutes(data.routes); setServices(data.services); } catch { setError("Le catalogue réseau est indisponible."); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const configured = services.filter((item) => item.pricing_count > 0).length;

  return <div className="min-h-full bg-[#f7f7f6]">
    <OperationPageHeader title="Routes et services" description="Configurez les corridors, délais, niveaux de service et règles tarifaires utilisés par toutes les opérations." actions={<><button className={button} onClick={() => setAction("simulate")}><Calculator size={14} />Simuler un tarif</button><PermissionGuard permission="routes.manage"><button className={primary} onClick={() => setAction("route")}><Plus size={14} />Nouvelle route</button></PermissionGuard></>} />
    <main className="py-4">
      <OperationMetrics><OperationMetricGrid><OperationMetric label="Routes actives" value={routes.filter((item) => item.active).length} active={view === "routes"} onClick={() => setView("routes")} /><OperationMetric label="Services disponibles" value={services.length} active={view === "services"} onClick={() => setView("services")} /><OperationMetric label="Services tarifés" value={`${configured}/${services.length}`} active={view === "services"} onClick={() => setView("services")} /></OperationMetricGrid></OperationMetrics>
      <OperationToolbar filters={<OperationFilterPopover activeCount={view === "routes" ? 0 : 1} onReset={() => setView("routes")} title="Filtrer le catalogue"><OperationField label="Vue"><select className={input} value={view} onChange={(event) => setView(event.target.value as "routes" | "services")}><option value="routes">Routes</option><option value="services">Services</option></select></OperationField></OperationFilterPopover>}><PermissionGuard permission="pricing.manage"><button className={button} onClick={() => setAction("price")}><Plus size={14} />Nouveau tarif</button></PermissionGuard><PermissionGuard permission="services.manage"><button className={button} onClick={() => setAction("service")}><Plus size={14} />Nouveau service</button></PermissionGuard><OperationButton onClick={load}><RefreshCcw size={14} />Actualiser</OperationButton></OperationToolbar>
      {error && <p className="mx-4 mb-3 bg-red-50 p-3 text-[13px] text-red-700">{error}</p>}
      {loading ? <LoadingState label="Chargement du réseau cargo…" /> : view === "routes" ? <RoutesTable items={routes} /> : <ServicesTable items={services} />}
    </main>
    <OperationDrawer open={Boolean(action)} title={action ? { route: "Nouvelle route", service: "Nouveau service", price: "Nouveau tarif", simulate: "Simulateur tarifaire" }[action] : ""} description="Configuration du catalogue réseau Slaivio" close={() => setAction(null)} width="max-w-xl">
      {action && <ActionForm kind={action} routes={routes} services={services} done={() => { setAction(null); load(); }} />}
    </OperationDrawer>
  </div>;
}

function RoutesTable({ items }: { items: Route[] }) { return <section className="overflow-x-auto border-y border-[#dfe1e3] bg-white">{items.length ? <table className="w-full min-w-[820px] text-left text-[13px]"><thead className="bg-[#f6f7f7] text-[#5f6976]"><tr>{["Code", "Corridor", "Mode", "Délai estimé", "Services", "État"].map((label) => <th className="px-4 py-3 font-medium" key={label}>{label}</th>)}</tr></thead><tbody>{items.map((item) => <tr className="border-t border-[#eceeef] hover:bg-[#fafafa]" key={item.id}><td className="px-4 py-3 font-semibold">{item.route_code}</td><td>{item.origin_city || item.origin_country} <span className="text-[#8a9097]">→</span> {item.destination_city || item.destination_country}<small className="block text-[#7a8188]">{item.route_name}</small></td><td>{item.transport_mode}</td><td>{item.eta_min_days}–{item.eta_max_days} jours</td><td>{item.service_count}</td><td><span className={`rounded-full px-2 py-1 text-[10px] font-medium ${item.active ? "bg-emerald-50 text-emerald-700" : "bg-[#f0f1f1] text-[#69717a]"}`}>{item.active ? "Active" : "Inactive"}</span></td></tr>)}</tbody></table> : <Empty icon={<RouteIcon size={22} />} title="Aucune route configurée" />}</section>; }
function ServicesTable({ items }: { items: Service[] }) { return <section className="overflow-x-auto border-y border-[#dfe1e3] bg-white">{items.length ? <table className="w-full min-w-[780px] text-left text-[13px]"><thead className="bg-[#f6f7f7] text-[#5f6976]"><tr>{["Service", "Route", "Mode", "Délai", "Tarification"].map((label) => <th className="px-4 py-3 font-medium" key={label}>{label}</th>)}</tr></thead><tbody>{items.map((item) => <tr className="border-t border-[#eceeef] hover:bg-[#fafafa]" key={item.id}><td className="px-4 py-3 font-semibold">{item.service_name}</td><td>{item.route_name}</td><td>{item.shipping_mode}</td><td>{item.eta_min_days}–{item.eta_max_days} jours</td><td>{item.pricing_count ? <span className="text-emerald-700">{item.pricing_count} composant(s)</span> : <span className="text-amber-700">À configurer</span>}</td></tr>)}</tbody></table> : <Empty icon={<Truck size={22} />} title="Aucun service configuré" />}</section>; }
function Empty({ icon, title }: { icon: ReactNode; title: string }) { return <div className="grid min-h-64 place-items-center text-center"><div className="text-[#9299a0]">{icon}<p className="mt-3 text-[13px] font-medium text-[#343a40]">{title}</p></div></div>; }

function ActionForm({ kind, routes, services, done }: { kind: Action; routes: Route[]; services: Service[]; done: () => void }) {
  const [result, setResult] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const form = new FormData(event.currentTarget), value = (key: string) => String(form.get(key) || ""), number = (key: string) => Number(form.get(key) || 0); try { if (kind === "route") await createRoute({ route_code: value("code"), route_name: value("name"), origin_country: value("origin_country"), origin_city: value("origin_city") || null, destination_country: value("destination_country"), destination_city: value("destination_city") || null, transport_mode: value("mode"), eta_min_days: number("eta_min"), eta_max_days: number("eta_max"), timezone: null, metadata: {} }); if (kind === "service") await createService({ route_id: value("route"), service_code: value("code"), service_name: value("name"), shipping_mode: value("mode"), service_type: "STANDARD", eta_min_days: number("eta_min"), eta_max_days: number("eta_max"), volumetric_divisor: number("divisor") || 6000, minimum_charge_minor: number("minimum"), currency_code: value("currency"), priority: 100, metadata: {} }); if (kind === "price") await addPrice(value("service"), { component_code: value("code"), component_name: value("name"), calculation_type: value("calculation"), amount_minor: Math.round(number("amount") * 100), currency_code: value("currency"), priority: 100, effective_from: new Date().toISOString(), metadata: {} }); if (kind === "simulate") { const response = await simulate({ service_id: value("service"), weight_kg: number("weight"), volume_cbm: number("volume") }); setResult(`${(response.total_minor / 100).toFixed(2)} ${response.currency} · poids facturable ${response.chargeable_weight_kg} kg`); return; } done(); } catch { setError("Cette opération n’a pas pu être enregistrée."); } finally { setBusy(false); } }
  return <form onSubmit={submit} className="grid gap-3 rounded-[6px] border border-[#dfe1e3] bg-white p-4">{["service", "price", "simulate"].includes(kind) && <select required name={kind === "service" ? "route" : "service"} className={input}><option value="">Sélectionner</option>{(kind === "service" ? routes : services).map((item) => <option key={item.id} value={item.id}>{"route_name" in item ? item.route_name : item.service_name}</option>)}</select>}{kind !== "simulate" && <><input required name="code" className={input} placeholder="Code unique" /><input required name="name" className={input} placeholder="Nom" /></>}{kind === "route" && <><FormGeographyFields required countryName="origin_country" cityName="origin_city" countryLabel="Pays d’origine" cityLabel="Ville d’origine" className={input}/><FormGeographyFields required countryName="destination_country" cityName="destination_city" countryLabel="Pays de destination" cityLabel="Ville de destination" className={input}/></>}{["route", "service"].includes(kind) && <><select name="mode" className={input}><option>AIR</option><option>SEA</option><option>EXPRESS</option><option>ROAD</option></select><input required type="number" name="eta_min" className={input} placeholder="Délai minimum en jours" /><input required type="number" name="eta_max" className={input} placeholder="Délai maximum en jours" /></>}{kind === "service" && <><input name="divisor" type="number" defaultValue="6000" className={input} /><input name="minimum" type="number" defaultValue="0" className={input} /><CurrencySelect/></>}{kind === "price" && <><select name="calculation" className={input}><option>PER_KG</option><option>PER_CBM</option><option>FIXED</option><option>PERCENTAGE</option></select><input required name="amount" type="number" step="0.01" className={input} placeholder="Montant" /><CurrencySelect/></>}{kind === "simulate" && <><input name="weight" type="number" step="0.001" className={input} placeholder="Poids en kg" /><input name="volume" type="number" step="0.0001" className={input} placeholder="Volume en CBM" /></>}<button disabled={busy} className={primary}>{busy ? "Traitement…" : kind === "simulate" ? "Calculer" : "Enregistrer"}</button>{error && <p className="bg-red-50 p-3 text-[12px] text-red-700">{error}</p>}{result && <p className="border border-emerald-200 bg-emerald-50 p-4 text-[13px] font-semibold text-emerald-800">{result}</p>}</form>;
}

function CurrencySelect() {
  return <select name="currency" defaultValue="USD" className={input} aria-label="Devise"><option value="USD">USD — Dollar américain</option><option value="EUR">EUR — Euro</option><option value="CDF">CDF — Franc congolais</option><option value="GBP">GBP — Livre sterling</option><option value="CNY">CNY — Yuan chinois</option><option value="AED">AED — Dirham des Émirats</option><option value="XAF">XAF — Franc CFA</option><option value="GHS">GHS — Cedi ghanéen</option><option value="KES">KES — Shilling kényan</option></select>;
}
