import {api} from "@/services/api";
import type {ExpeditionDetail} from "@/services/shipments";
export type TrackingItem={id:string;tracking_id:string;type:"SHIPMENT";title:string|null;status:string;mode:string;risk_level:string;origin_country:string|null;origin_city:string|null;destination_country:string|null;destination_city:string|null;route_label:string|null;origin_warehouse:string|null;destination_warehouse:string|null;last_location:string|null;eta_at:string|null;progress_percent:number;is_delayed:boolean;delay_hours:number;delay_reason:string|null;owner_name:string|null;container_number:string|null;batch_reference:string|null;packages_count:number;clients_count:number;total_weight_kg:number;total_volume_cbm:number;updated_at:string;last_signal_at:string;last_signal_source:string;open_alerts:number};
export type TrackingStats={packages_in_transit:number;active_shipments:number;delivered_today:number;delays:number;incidents_open:number;average_transit_hours:number|null};
export type TrackingEvent={id:string;expedition_id:string;tracking_id:string;event_type:string;title:string;description:string|null;actor_name:string|null;metadata:Record<string,unknown>;occurred_at:string;location:string|null};
export type TrackingResponse={items:TrackingItem[];pagination:{page:number;page_size:number;total:number;total_pages:number}};
export type TrackingFilters={q?:string;status?:string;risk_level?:string;country?:string;route?:string;warehouse?:string;client_id?:string;container?:string;batch?:string;incident?:boolean;date_from?:string;date_to?:string;page?:number;page_size?:number};
export type TrackingAlert={id:string;expedition_id:string;tracking_id:string;anomaly_type:string;severity:"LOW"|"MEDIUM"|"HIGH"|"CRITICAL";status:"OPEN"|"IN_REVIEW"|"RESOLVED"|"DISMISSED";title:string;description:string|null;assigned_to:string|null;assigned_name:string|null;resolution_notes:string|null;detected_at:string;resolved_at:string|null;history:Array<{action:string;previous_status:string|null;new_status:string|null;comment:string|null;actor_id:string|null;created_at:string}>};
export type TrackingAnalytics={summary:{delivered:number;delivered_on_time:number;delayed:number;mean_resolution_hours:number|null};best_routes:Array<{label:string;count:number}>;delays_by_route:Array<{label:string;count:number}>;delays_by_country:Array<{label:string;count:number}>;delays_by_warehouse:Array<{label:string;count:number}>;incidents_by_type:Array<{label:string;count:number}>;deliveries:Array<{label:string;count:number}>};
export type TrackingSavedView={id:string;name:string;filters:TrackingFilters;is_default:boolean;created_at:string;updated_at:string};
export async function listTracking(params:Record<string,unknown>={}){return (await api.get<TrackingResponse>("/tracking",{params})).data}
export async function getTrackingStats(){return (await api.get<{stats:TrackingStats}>("/tracking/stats")).data.stats}
export async function getGlobalTrackingTimeline(){return (await api.get<{items:TrackingEvent[]}>("/tracking/timeline")).data.items}
export async function exportTracking(params:TrackingFilters={}){return (await api.get<Blob>("/tracking/export",{params,responseType:"blob"})).data}
export async function getTracking(id:string){return (await api.get<{tracking:ExpeditionDetail}>(`/tracking/${id}`)).data.tracking}
export async function getTrackingAnalytics(){return (await api.get<{analytics:TrackingAnalytics}>("/tracking/analytics")).data.analytics}
export async function listTrackingAlerts(params:Record<string,unknown>={}){return (await api.get<{items:TrackingAlert[]}>("/tracking/alerts",{params})).data.items}
export async function detectTrackingAlerts(){return (await api.post<{created:number}>("/tracking/alerts/detect")).data}
export async function listTrackingViews(){return (await api.get<{items:TrackingSavedView[]}>("/tracking/views")).data.items}
export async function saveTrackingView(name:string,filters:TrackingFilters){return (await api.post<{view:TrackingSavedView}>("/tracking/views",{name,filters})).data.view}
export async function createTrackingAlert(id:string,payload:{severity:string;title:string;description?:string}){return (await api.post(`/tracking/${id}/alerts`,payload)).data.tracking}
export async function createTrackingEvent(id:string,payload:{event_type:string;title:string;description?:string;location?:string;occurred_at?:string;idempotency_key?:string}){return (await api.post(`/tracking/${id}/events`,payload)).data.tracking}
export async function createTrackingNotification(id:string,payload:{channel:string;audience:string;recipient?:string;message:string}){return (await api.post(`/tracking/${id}/notifications`,payload)).data.tracking}
export async function generatePublicTrackingToken(id:string,expires_at?:string){return (await api.post<{public_tracking_token:string;tracking_path:string}>(`/tracking/${id}/public-token`,{expires_at})).data}
export async function updateTrackingEta(id:string,eta_at:string,reason:string,expected_version?:number){return (await api.patch<{tracking:ExpeditionDetail}>(`/tracking/${id}/eta`,{eta_at,reason,expected_version})).data.tracking}
export async function assignTracking(id:string,owner_id:string,owner_name:string,expected_version?:number){return (await api.patch<{tracking:ExpeditionDetail}>(`/tracking/${id}/assignment`,{owner_id,owner_name,expected_version})).data.tracking}
export async function updateTrackingAlert(id:string,alertId:string,payload:{status?:string;assigned_to?:string;assigned_name?:string;comment?:string}){return (await api.patch<{tracking:ExpeditionDetail}>(`/tracking/${id}/alerts/${alertId}`,payload)).data.tracking}
export async function addTrackingNote(id:string,note:string,priority="NORMAL"){return (await api.post<{tracking:ExpeditionDetail}>(`/tracking/${id}/notes`,{note,priority})).data.tracking}
export async function addTrackingDocument(id:string,payload:{document_type:string;file_url:string;file_name?:string;mime_type?:string;visibility?:string;notes?:string}){return (await api.post<{tracking:ExpeditionDetail}>(`/tracking/${id}/documents`,payload)).data.tracking}
export async function uploadTrackingDocument(id:string,file:File,document_type="DOCUMENT",notes?:string){const form=new FormData();form.append("file",file);form.append("document_type",document_type);if(notes)form.append("notes",notes);return (await api.post<{tracking:ExpeditionDetail}>(`/tracking/${id}/documents/upload`,form)).data.tracking}
export async function getTrackingDocumentUrl(id:string,documentId:string){return (await api.get<{url:string}>(`/tracking/${id}/documents/${documentId}/view`)).data.url}
export async function disablePublicTrackingToken(id:string){return (await api.delete<{tracking:ExpeditionDetail}>(`/tracking/${id}/public-token`)).data.tracking}
export async function archiveTracking(id:string){await api.delete(`/tracking/${id}`)}
export async function notifyTrackingBulk(tracking_ids:string[],payload:{channel:string;audience:string;recipient?:string;message:string}){return (await api.post<{count:number}>("/tracking/notifications/bulk",{tracking_ids,...payload})).data}
export async function getPublicTracking(token:string){return (await api.get<{tracking:TrackingItem&{events:Array<{event_type:string;title:string;description:string|null;occurred_at:string}>}}>(`/public/tracking/${token}`)).data.tracking}
export type PublicPackageTracking={agency_name:string;agency_logo_url:string|null;package_reference:string;tracking_id:string|null;status:string;origin_city:string|null;origin_country:string|null;destination_city:string|null;destination_country:string|null;eta_at:string|null;received_at:string|null;dispatched_at:string|null;delivered_at:string|null;last_scan_location:string|null;updated_at:string;events:Array<{event_type:string;title:string;description:string|null;new_status:string|null;occurred_at:string}>};
export async function findPublicPackageTracking(reference:string){return (await api.get<{tracking:PublicPackageTracking}>(`/public/packages/tracking/${encodeURIComponent(reference.trim())}`)).data.tracking}
