"use client";

import axios from "axios";
import {AlertTriangle,ChevronRight,Download,RefreshCcw,Save,Send} from "lucide-react";
import Link from "next/link";
import {FormEvent,useCallback,useEffect,useState} from "react";
import {PermissionGuard} from "@/components/permissions/permission-guard";
import {OperationPageHeader} from "@/components/ui/operation-page-header";
import {OperationDrawer} from "@/components/ui/operation-drawer";
import {OperationMetrics,OperationTable,OperationToolbar,OperationSearch} from "@/components/ui/operation-primitives";
import {OperationActionMenu,OperationButton,OperationField,OperationFilterPopover,OperationMetric,OperationMetricGrid} from "@/components/ui/operation-controls";
import {ErrorState,TableSkeleton} from "@/components/ui/page-state";
import {businessLabel} from "@/components/ui/business-labels";
import {detectTrackingAlerts,exportTracking,getGlobalTrackingTimeline,getTrackingAnalytics,getTrackingStats,listTracking,listTrackingAlerts,listTrackingViews,notifyTrackingBulk,saveTrackingView,type TrackingAlert,type TrackingAnalytics,type TrackingEvent,type TrackingFilters,type TrackingItem,type TrackingSavedView,type TrackingStats} from "@/services/tracking";

const button="inline-flex h-9 items-center justify-center gap-2 rounded-md border border-[#cfd5dd] bg-white px-3 text-[13px] font-medium shadow-sm hover:bg-[#f7f8fa] disabled:cursor-not-allowed disabled:opacity-50";
const primary="inline-flex h-9 items-center justify-center gap-2 rounded-md bg-[#12c76f] px-3 text-[13px] font-semibold text-white hover:bg-[#0fb966] disabled:opacity-50";
const input="h-9 rounded-md border border-[#cfd5dd] bg-white px-3 text-[13px] outline-none focus:border-[#12a865]";
const emptyStats:TrackingStats={packages_in_transit:0,active_shipments:0,delivered_today:0,delays:0,incidents_open:0,average_transit_hours:null};
type View="control"|"map"|"timeline"|"alerts"|"analytics";

export function TrackingPage(){
 const [items,setItems]=useState<TrackingItem[]>([]),[events,setEvents]=useState<TrackingEvent[]>([]),[alerts,setAlerts]=useState<TrackingAlert[]>([]),[analytics,setAnalytics]=useState<TrackingAnalytics|null>(null),[stats,setStats]=useState(emptyStats),[savedViews,setSavedViews]=useState<TrackingSavedView[]>([]);
 const [filters,setFilters]=useState<TrackingFilters>({}),[view,setView]=useState<View>("control"),[selected,setSelected]=useState<string[]>([]),[page,setPage]=useState(1),[pages,setPages]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notifyOpen,setNotifyOpen]=useState(false),[filtersOpen,setFiltersOpen]=useState(false),[allMetrics,setAllMetrics]=useState(false);
 const load=useCallback(async(next=1)=>{setLoading(true);setError("");try{const [list,kpis,timeline,alertList,metrics,views]=await Promise.all([listTracking({...filters,page:next}),getTrackingStats(),getGlobalTrackingTimeline(),listTrackingAlerts(),getTrackingAnalytics(),listTrackingViews()]);setItems(list.items);setPages(list.pagination.total_pages);setPage(next);setStats(kpis);setEvents(timeline);setAlerts(alertList);setAnalytics(metrics);setSavedViews(views)}catch(e){setError(message(e))}finally{setLoading(false)}},[filters]);
 useEffect(()=>{const id=setTimeout(()=>load(1),250);return()=>clearTimeout(id)},[filters,load]);
 useEffect(()=>{const id=window.setInterval(async()=>{try{const [nextAlerts,nextStats]=await Promise.all([listTrackingAlerts(),getTrackingStats()]);setAlerts(nextAlerts);setStats(nextStats)}catch{/* The visible error state remains reserved for user-triggered loads. */}},30000);return()=>window.clearInterval(id)},[]);
 const cards=[['Expéditions actives',stats.active_shipments],['Colis en transit',stats.packages_in_transit],['Retards',stats.delays],['Incidents ouverts',stats.incidents_open],['Livraisons aujourd’hui',stats.delivered_today],['Transit moyen',stats.average_transit_hours==null?'—':`${stats.average_transit_hours} h`]];
 async function download(){try{const blob=await exportTracking(filters);const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="slaivio-tracking.csv";a.click();URL.revokeObjectURL(url)}catch(e){setError(message(e))}}
 async function saveView(){const name=window.prompt("Nom de la vue");if(!name)return;try{const saved=await saveTrackingView(name,filters);setSavedViews(current=>[saved,...current.filter(item=>item.id!==saved.id)])}catch(e){setError(message(e))}}
 async function detect(){try{await detectTrackingAlerts();await load()}catch(e){setError(message(e))}}
 return <div className="min-h-full bg-[#f7f7f6] text-[#1f2328]">
  <OperationPageHeader title="Tracking" description="Supervisez en temps réel tous les colis, expéditions et mouvements logistiques." actions={<><OperationActionMenu><PermissionGuard permission="tracking.update"><button onClick={saveView}><Save size={14}/>Enregistrer la vue</button></PermissionGuard></OperationActionMenu><PermissionGuard permission="tracking.export"><OperationButton onClick={download}><Download size={14}/>Exporter CSV</OperationButton></PermissionGuard></>}/>
  <OperationMetrics><OperationMetricGrid className={allMetrics?'lg:grid-cols-6':'lg:grid-cols-4'}>{cards.slice(0,allMetrics?6:4).map(([label,value])=>{const target=String(label).toLowerCase().includes('alerte')?'alerts':'control';return <OperationMetric key={String(label)} label={String(label)} value={value} active={view===target} onClick={()=>setView(target)}/>})}</OperationMetricGrid><button onClick={()=>setAllMetrics(value=>!value)} className="mt-3 text-[11px] font-medium text-[#087a46]">{allMetrics?'Réduire les indicateurs':'Voir tous les indicateurs'}</button></OperationMetrics>
  {error&&<ErrorState title="Tracking indisponible" description={error} retry={()=>load()}/>}
  <Filters filters={filters} setFilters={setFilters} view={view} setView={setView} stats={stats} savedViews={savedViews} saveView={saveView} open={filtersOpen} setOpen={setFiltersOpen} refresh={()=>load()}/>
  {view==='control'&&<>
   <TrackingTable items={items} loading={loading} selected={selected} setSelected={setSelected}/>
   <footer className="flex items-center justify-between bg-white px-4 py-3"><span className="text-[12px] text-[#66717e]">{selected.length} sélection(s)</span><div className="flex gap-2">{selected.length>0&&<PermissionGuard permission="tracking.notify"><button className={primary} onClick={()=>setNotifyOpen(true)}><Send size={14}/>Notifier</button></PermissionGuard>}<button disabled={page<=1} onClick={()=>load(page-1)} className={button}>Précédent</button><span className="px-3 py-2 text-[13px]">{page}/{Math.max(pages,1)}</span><button disabled={page>=pages} onClick={()=>load(page+1)} className={button}>Suivant</button></div></footer>
  </>}
  {view==='map'&&<RouteMap routes={items}/>} {view==='timeline'&&<Timeline events={events}/>} {view==='alerts'&&<AlertsCenter alerts={alerts} onDetect={detect}/>} {view==='analytics'&&<Analytics data={analytics}/>}
  {notifyOpen&&<BulkNotify ids={selected} onClose={()=>setNotifyOpen(false)} onDone={()=>{setNotifyOpen(false);setSelected([])}}/>}
 </div>
}

function Filters({filters,setFilters,view,setView,stats,savedViews,saveView,open,setOpen,refresh}:{filters:TrackingFilters;setFilters:(value:TrackingFilters)=>void;view:View;setView:(value:View)=>void;stats:TrackingStats;savedViews:TrackingSavedView[];saveView:()=>void;open:boolean;setOpen:(value:boolean)=>void;refresh:()=>void}){
 const set=(key:keyof TrackingFilters,value:string|boolean|undefined)=>setFilters({...filters,[key]:value||undefined});
 const active=Object.entries(filters).filter(([key,value])=>key!=="q"&&value!==undefined&&value!=="").length+(view==='control'?0:1);
 return <OperationToolbar search={<OperationSearch value={filters.q||''} onChange={value=>set('q',value)} placeholder="Rechercher un colis, une expédition ou un client…"/>} filters={<><OperationFilterPopover open={open} onOpenChange={setOpen} activeCount={active} onReset={()=>{setFilters(filters.q?{q:filters.q}:{});setView('control')}} title="Filtrer les suivis">
  <OperationField label="Vue"><select className={`${input} w-full`} value={view} onChange={e=>setView(e.target.value as View)}><option value="control">Suivis</option><option value="map">Carte</option><option value="timeline">Timeline</option><option value="alerts">Alertes{stats.incidents_open?` · ${stats.incidents_open}`:''}</option><option value="analytics">Analytics</option></select></OperationField>
  <OperationField label="Étape du transport"><select className={`${input} w-full`} value={filters.status||''} onChange={e=>set('status',e.target.value)}><option value="">Toutes les étapes</option>{[['PREPARING','Préparation'],['LOADING','Chargement'],['DISPATCHED','Expédié'],['IN_TRANSIT','En transit'],['CUSTOMS_CLEARANCE','Dédouanement'],['DELIVERED','Livré'],['BLOCKED','Bloqué']].map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></OperationField>
  <OperationField label="Niveau de risque"><select className={`${input} w-full`} value={filters.risk_level||''} onChange={e=>set('risk_level',e.target.value)}><option value="">Tous les niveaux</option>{[['LOW','Faible'],['MEDIUM','Moyen'],['HIGH','Élevé'],['CRITICAL','Critique']].map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></OperationField>
  <label className="flex items-center gap-3 rounded-md bg-[#f6f8fa] px-3 py-3 text-[13px] font-medium text-[#344054]"><input type="checkbox" checked={Boolean(filters.incident)} onChange={e=>set('incident',e.target.checked||undefined)}/>Uniquement les suivis avec incident</label>
  <div className="grid gap-4 sm:grid-cols-2"><OperationField label="Depuis"><input type="date" className={`${input} w-full`} value={filters.date_from||''} onChange={e=>set('date_from',e.target.value)}/></OperationField><OperationField label="Jusqu’au"><input type="date" className={`${input} w-full`} value={filters.date_to||''} onChange={e=>set('date_to',e.target.value)}/></OperationField></div>
  <PermissionGuard permission="tracking.update"><button onClick={saveView} className="text-left text-[12px] font-semibold text-[#087a46]">Enregistrer ces filtres comme vue</button></PermissionGuard>
 </OperationFilterPopover>{savedViews.length>0&&<select aria-label="Vues enregistrées" className={input} defaultValue="" onChange={e=>{const selected=savedViews.find(view=>view.id===e.target.value);if(selected)setFilters(selected.filters)}}><option value="">Vues enregistrées</option>{savedViews.map(view=><option value={view.id} key={view.id}>{view.name}</option>)}</select>}</>}><OperationButton onClick={refresh}><RefreshCcw size={14}/>Actualiser</OperationButton></OperationToolbar>
}
function RouteMap({routes}:{routes:TrackingItem[]}){return <div className="p-5"><div className="relative min-h-[520px] overflow-hidden rounded-lg bg-[radial-gradient(circle_at_20%_30%,#e7f0ff,transparent_24%),radial-gradient(circle_at_75%_65%,#e7f8ef,transparent_28%),#f8fafc] p-8"><div className="absolute inset-0 opacity-20 [background-image:linear-gradient(#94a3b8_1px,transparent_1px),linear-gradient(90deg,#94a3b8_1px,transparent_1px)] [background-size:40px_40px]"/><div className="relative grid gap-3 md:grid-cols-2 xl:grid-cols-3">{routes.map(r=><Link key={r.id} href={`/app/tracking/${r.id}`} className="rounded-lg bg-white/95 p-4 shadow-[0_3px_14px_rgba(15,23,42,.08)]"><div className="flex items-center gap-2"><RiskDot item={r}/><b>{r.tracking_id}</b></div><p className="mt-3 text-[13px]">{r.origin_city||r.origin_country||'Origine'} → {r.destination_city||r.destination_country||'Destination'}</p><p className="mt-1 text-[12px] text-[#687584]">Position : {r.last_location||'inconnue'} · {r.progress_percent}%</p></Link>)}</div>{!routes.length&&<Empty text="Aucune route active à cartographier."/>}</div></div>}
function Timeline({events,embedded=false}:{events:TrackingEvent[];embedded?:boolean}){return <div className={`${embedded?'max-h-[292px]':'mx-auto max-w-4xl p-6'} overflow-y-auto`}>{events.length?events.map(e=><Link href={`/app/tracking/${e.expedition_id}`} key={e.id} className="relative block border-l border-[#cbd3dc] py-3 pl-5 before:absolute before:-left-[5px] before:top-5 before:h-2.5 before:w-2.5 before:rounded-full before:bg-[#16855f]"><div className="flex justify-between gap-4 text-[13px]"><b>{e.tracking_id} · {e.title}</b><time className="text-[11px] text-[#687584]">{formatDate(e.occurred_at)}</time></div><p className="mt-1 text-[12px] text-[#687584]">{e.location||e.description||businessLabel(e.event_type)}</p></Link>):<Empty text="Aucun événement enregistré."/>}</div>}

function TrackingTable({items,loading,selected,setSelected}:{items:TrackingItem[];loading:boolean;selected:string[];setSelected:(ids:string[])=>void}){const all=items.length>0&&items.every(i=>selected.includes(i.id));if(loading)return <TableSkeleton rows={7} columns={10} label="Chargement des suivis…"/>;if(!items.length)return <div className="bg-white"><Empty text="Aucun suivi trouvé. Modifiez les filtres ou créez une expédition active."/></div>;return <OperationTable><table className="min-w-[1160px] w-full text-left text-[13px]"><thead className="border-b bg-[#f7f8fa] text-[#59636e]"><tr><th className="px-4"><input type="checkbox" checked={all} onChange={()=>setSelected(all?[]:items.map(i=>i.id))}/></th>{['Tracking ID','Type','Origine','Destination','Dernière position','Statut','ETA','Signal','Alertes',''].map((h,index)=><th key={`${h}-${index}`} className="px-4 py-3 font-medium">{h}</th>)}</tr></thead><tbody>{items.map(r=><tr key={r.id} className="h-11 border-b hover:bg-[#fafafa]"><td className="px-4"><input type="checkbox" checked={selected.includes(r.id)} onChange={()=>setSelected(selected.includes(r.id)?selected.filter(id=>id!==r.id):[...selected,r.id])}/></td><td className="px-4 py-3 font-semibold">{r.tracking_id}</td><td className="px-4">Expédition</td><td className="px-4">{r.origin_city||r.origin_country||'—'}</td><td className="px-4">{r.destination_city||r.destination_country||'—'}</td><td className="px-4">{r.last_location||'—'}</td><td className="px-4"><Status item={r}/></td><td className="px-4">{formatDate(r.eta_at)}</td><td className="px-4">{freshness(r.last_signal_at)}</td><td className="px-4">{r.open_alerts}</td><td className="px-3 text-right"><Link href={`/app/tracking/${r.id}`} aria-label={`Voir ${r.tracking_id}`} className="inline-grid h-8 w-8 place-items-center rounded-[6px] text-[#66717e] hover:bg-[#eef1f3] hover:text-[#087a46]"><ChevronRight size={16}/></Link></td></tr>)}</tbody></table></OperationTable>}

function AlertsCenter({alerts,onDetect}:{alerts:TrackingAlert[];onDetect:()=>void}){const [status,setStatus]=useState("");const [severity,setSeverity]=useState("");const shown=alerts.filter(a=>(!status||a.status===status)&&(!severity||a.severity===severity));return <div className="p-5"><div className="mb-4 flex flex-wrap gap-2"><select className={input} value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tous les états</option>{['OPEN','IN_REVIEW','RESOLVED','DISMISSED'].map(v=><option key={v}>{v}</option>)}</select><select className={input} value={severity} onChange={e=>setSeverity(e.target.value)}><option value="">Toutes les sévérités</option>{['LOW','MEDIUM','HIGH','CRITICAL'].map(v=><option key={v}>{v}</option>)}</select><PermissionGuard permission="tracking.alerts"><button onClick={onDetect} className={button}><AlertTriangle size={15}/>Lancer la détection</button></PermissionGuard></div><div className="overflow-hidden rounded-lg bg-white shadow-[0_1px_2px_rgba(15,23,42,.04)]">{shown.map(a=><Link href={`/app/tracking/${a.expedition_id}?tab=Alerts`} key={a.id} className="grid gap-3 border-b border-[#eff1f3] p-4 last:border-0 hover:bg-[#fafbfc] md:grid-cols-[120px_1fr_150px_140px]"><span className={`w-fit rounded px-2 py-1 text-[11px] font-semibold ${a.severity==='CRITICAL'?'bg-red-100 text-red-700':a.severity==='HIGH'?'bg-orange-100 text-orange-700':'bg-amber-50 text-amber-700'}`}>{a.severity}</span><div><b className="text-[13px]">{a.title}</b><p className="text-[12px] text-[#687584]">{a.tracking_id} · {a.description||'Sans description'}</p></div><span className="text-[12px]">{a.assigned_name||'Non assignée'}</span><span className="text-[12px]">{a.status}</span></Link>)}{!shown.length&&<Empty text="Aucune alerte dans cette vue."/>}</div></div>}
function Analytics({data}:{data:TrackingAnalytics|null}){if(!data)return <Empty text="Analytics indisponibles."/>;const delivered=data.summary.delivered||0;const rate=Math.round((data.summary.delivered_on_time/delivered)*100)||0;return <div className="grid gap-4 p-5 lg:grid-cols-2"><Metric title="Respect des ETA" value={`${rate}%`}/><Metric title="Résolution moyenne" value={data.summary.mean_resolution_hours==null?'—':`${data.summary.mean_resolution_hours} h`}/><Rows title="Routes les plus fiables (% à l’heure)" rows={data.best_routes}/><Rows title="Routes les plus problématiques" rows={data.delays_by_route}/><Rows title="Retards par pays" rows={data.delays_by_country}/><Rows title="Retards par entrepôt" rows={data.delays_by_warehouse}/><Rows title="Incidents par catégorie" rows={data.incidents_by_type}/><Rows title="Livraisons sur 30 jours" rows={data.deliveries}/></div>}
function BulkNotify({ids,onClose,onDone}:{ids:string[];onClose:()=>void;onDone:()=>void}){const [error,setError]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await notifyTrackingBulk(ids,{channel:String(f.get('channel')),audience:'ALL_CLIENTS',message:String(f.get('message'))});onDone()}catch(x){setError(message(x))}}return <Modal title={`Notifier ${ids.length} suivi(s)`} onClose={onClose}><form onSubmit={submit} className="space-y-3"><select name="channel" className={`${input} w-full`}><option value="whatsapp">WhatsApp</option><option value="email">Email</option><option value="internal">Interne</option></select><textarea required name="message" className="min-h-28 w-full rounded-md border p-3 text-[13px]" placeholder="Message opérationnel"/>{error&&<p className="text-red-600">{error}</p>}<button className={`${primary} w-full`}><Send size={14}/>Envoyer</button></form></Modal>}
function RiskDot({item}:{item:TrackingItem}){return <span className={`h-2.5 w-2.5 shrink-0 rounded-full ${item.is_delayed?'bg-red-500':item.risk_level==='HIGH'||item.risk_level==='CRITICAL'?'bg-orange-500':'bg-emerald-500'}`}/>}
function Status({item}:{item:TrackingItem}){return <span className={`rounded-full px-2 py-1 text-[11px] ${item.is_delayed?'bg-red-50 text-red-700':item.risk_level==='HIGH'||item.risk_level==='CRITICAL'?'bg-orange-50 text-orange-700':'bg-emerald-50 text-emerald-700'}`}>{businessLabel(item.status)}</span>}
function Empty({text}:{text:string}){return <div className="flex min-h-40 items-center justify-center p-8 text-center text-[13px] text-[#77828e]">{text}</div>}
function Metric({title,value}:{title:string;value:string}){return <article className="rounded-lg bg-white p-5 shadow-[0_1px_2px_rgba(15,23,42,.04)]"><p className="text-[12px] text-[#687584]">{title}</p><p className="mt-2 text-3xl">{value}</p></article>}
function Rows({title,rows}:{title:string;rows:Array<{label:string;count:number}>}){return <article className="rounded-lg bg-white p-5 shadow-[0_1px_2px_rgba(15,23,42,.04)]"><h3 className="mb-3 text-[14px] font-semibold">{title}</h3>{rows.map(r=><div key={r.label} className="flex justify-between border-b border-[#f0f1f3] py-2 text-[12px]"><span>{r.label}</span><b>{r.count}</b></div>)}{!rows.length&&<p className="text-[12px] text-[#77828e]">Aucune donnée.</p>}</article>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <OperationDrawer open title={title} close={onClose}>{children}</OperationDrawer>}
function freshness(value:string){const minutes=(Date.now()-new Date(value).getTime())/60000;return minutes<15?'Temps réel':minutes<180?'Récent':minutes<1440?'Ancien':'Signal perdu'}
function formatDate(value?:string|null){if(!value)return'—';return new Intl.DateTimeFormat('fr-FR',{dateStyle:'short',timeStyle:'short'}).format(new Date(value))}
function message(error:unknown){if(axios.isAxiosError(error))return String(error.response?.data?.detail||error.message);return error instanceof Error?error.message:'Erreur inattendue'}
