"use client";

import { Building2, Check, ChevronDown, Network, Plus, Settings2, X } from "lucide-react";
import Link from "next/link";
import { useCallback, useEffect, useRef, useState } from "react";

import { usePermissions } from "@/components/permissions/permission-provider";
import { FormGeographyFields, PhoneField } from "@/components/ui/geography-fields";
import { OperationButton } from "@/components/ui/operation-controls";
import { OperationDrawer } from "@/components/ui/operation-drawer";
import { createNetworkOffice } from "@/services/organization-network";
import { createTenant, getTenantContext, switchTenant } from "@/services/tenant";

type Tenant = { org_id:string; organization_name?:string|null; organization_type?:string|null; role_code?:string|null; group_id?:string|null; network_name?:string|null; country?:string|null; city?:string|null };
const inputClass="h-10 w-full rounded-[7px] border border-[#d4d9df] bg-white px-3 text-[13px] outline-none focus:border-[#12a865] focus:ring-2 focus:ring-[#12c76f]/10";

export function formatOrganizationDisplayName(value?:string|null){const normalized=value?.trim().replace(/\s+/g," ").toLowerCase();if(!normalized)return "organisation";return normalized.endsWith("'s org")?normalized:`${normalized}'s org`;}
function officeName(tenant?:Tenant|null){return tenant?.organization_name?.trim()||"Bureau";}

export function OrganizationSwitcher({collapsed=false,menuPlacement="up",header=false}:{collapsed?:boolean;menuPlacement?:"up"|"down";header?:boolean}){
  const rootRef=useRef<HTMLDivElement>(null);
  const {permissions,available}=usePermissions();
  const [tenants,setTenants]=useState<Tenant[]>([]);const [activeTenant,setActiveTenant]=useState<Tenant|null>(null);
  const [loading,setLoading]=useState(true);const [switching,setSwitching]=useState(false);const [open,setOpen]=useState(false);const [createOpen,setCreateOpen]=useState(false);
  const [organizationName,setOrganizationName]=useState("");const [creating,setCreating]=useState(false);const [error,setError]=useState("");
  const parcelFreight=activeTenant?.organization_type==="PARCEL_FREIGHT";const networkConfigured=parcelFreight&&Boolean(activeTenant?.group_id);
  const canCreateOffice=networkConfigured&&available&&permissions.includes("network.offices.manage");
  const networkTenants=activeTenant?.group_id?tenants.filter(tenant=>tenant.group_id===activeTenant.group_id):[];
  const otherTenants=activeTenant?.group_id?tenants.filter(tenant=>tenant.group_id!==activeTenant.group_id):tenants;
  const activeLabel=parcelFreight?officeName(activeTenant):formatOrganizationDisplayName(activeTenant?.organization_name);

  const load=useCallback(async()=>{try{const data=await getTenantContext();setTenants(data.tenants||[]);setActiveTenant(data.active_tenant||null);setError("");}catch{setError("Espaces indisponibles");}finally{setLoading(false);}},[]);
  useEffect(()=>{load();},[load]);
  useEffect(()=>{function outside(event:MouseEvent){if(!rootRef.current?.contains(event.target as Node))setOpen(false);}document.addEventListener("mousedown",outside);return()=>document.removeEventListener("mousedown",outside);},[]);

  async function handleSwitch(tenant:Tenant){if(tenant.org_id===activeTenant?.org_id){setOpen(false);return;}setSwitching(true);setError("");try{await switchTenant(tenant.org_id);window.sessionStorage.removeItem("slaivio:dashboard-home");window.location.reload();}catch{setError("Changement impossible");setSwitching(false);}}
  async function handleCreate(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);setCreating(true);setError("");try{if(networkConfigured){const value=(key:string)=>String(form.get(key)||"").trim();await createNetworkOffice({organization_name:value("organization_name"),office_code:value("office_code"),country:value("country"),country_code:value("country_code"),city:value("city"),currency_code:value("currency_code")||"USD",timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||"UTC",address:[value("address_line_1"),value("address_line_2")].filter(Boolean).join("\n")||null,phone:value("phone")||null,email:value("email")||null});setCreateOpen(false);await load();}else{const name=organizationName.trim();if(name.length<2){setError("Saisissez un nom d’organisation.");return;}await createTenant(name);window.sessionStorage.removeItem("slaivio:dashboard-home");window.location.assign("/onboarding");}}catch{setError(networkConfigured?"La création du bureau a échoué.":"La création de l’organisation a échoué.");}finally{setCreating(false);}}
  function tenantRow(tenant:Tenant,rawOfficeName=false){return <button key={tenant.org_id} type="button" onClick={()=>handleSwitch(tenant)} className="flex min-h-11 w-full items-center gap-2 rounded-[6px] px-2 text-left hover:bg-[#f3f4f4]"><Building2 size={15} className="shrink-0 text-[#686e75]"/><span className="min-w-0 flex-1"><span className="block truncate text-[13px] font-medium">{rawOfficeName?officeName(tenant):formatOrganizationDisplayName(tenant.organization_name)}</span>{(tenant.city||tenant.country)&&<span className="mt-0.5 block truncate text-[11px] text-[#7b838b]">{[tenant.city,tenant.country].filter(Boolean).join(" · ")} · {tenant.role_code||"MEMBRE"}</span>}</span>{tenant.org_id===activeTenant?.org_id&&<Check size={15} className="shrink-0 text-[#16855f]"/>}</button>;}

  return <div ref={rootRef} className={`relative ${collapsed?"lg:p-0":""} ${header?"w-[min(190px,44vw)]":""}`}>
    <button type="button" onClick={()=>setOpen(value=>!value)} disabled={loading||switching} aria-expanded={open} title={collapsed?activeLabel:undefined} className={`flex w-full items-center rounded-[6px] border border-[#d8dadd] bg-white text-left shadow-[0_1px_1px_rgba(15,23,42,.03)] hover:border-[#c7cbcf] hover:bg-[#f7f7f6] disabled:opacity-60 ${header?"min-h-9 gap-2 px-3":"min-h-11"} ${collapsed?"lg:justify-center lg:px-1":header?"":"gap-2 px-3"}`}>
      {(collapsed||header)&&<Building2 size={16} className={`${collapsed?"hidden lg:block":""} shrink-0 text-[#16855f]`}/>}<span className={`min-w-0 flex-1 ${collapsed?"lg:hidden":""}`}>{networkConfigured&&<span className="block truncate text-[10px] font-medium uppercase tracking-[.08em] text-[#849089]">{activeTenant?.network_name||"Réseau"}</span>}<span className="block truncate text-[13px] font-medium text-[#25292e]">{loading?"Chargement...":activeTenant?activeLabel:"aucune organisation"}</span></span><ChevronDown size={15} className={`shrink-0 text-[#73777c] transition ${collapsed?"lg:hidden":""} ${open?"rotate-180":""}`}/>
    </button>
    {open&&<div className={`absolute z-50 w-[280px] overflow-hidden rounded-[8px] border border-[#d2d5d8] bg-white shadow-[0_14px_38px_rgba(15,23,42,.16)] ${collapsed?"bottom-0 left-[48px]":menuPlacement==="down"?header?"right-0 top-[44px]":"left-0 top-[52px]":"bottom-[52px] left-0"}`}><div className="flex min-h-11 items-center border-b border-[#eceeed] px-3 text-[12px] font-semibold text-[#454e55]">{networkConfigured?activeTenant?.network_name||"Bureaux du réseau":"Vos organisations"}<button type="button" onClick={()=>setOpen(false)} className="ml-auto rounded p-1 hover:bg-[#f0f1f1]" aria-label="Fermer"><X size={14}/></button></div><div className="max-h-72 overflow-y-auto p-1.5">{networkConfigured&&<><p className="px-2 pb-1 pt-1 text-[10px] font-semibold uppercase tracking-[.08em] text-[#8a9298]">Bureaux accessibles</p>{networkTenants.map(tenant=>tenantRow(tenant,true))}</>}{networkConfigured&&otherTenants.length>0&&<p className="mt-1 border-t border-[#eceeed] px-2 pb-1 pt-2 text-[10px] font-semibold uppercase tracking-[.08em] text-[#8a9298]">Autres entreprises</p>}{(networkConfigured?otherTenants:tenants).map(tenant=>tenantRow(tenant,false))}</div><div className="border-t border-[#eceeed] p-1.5">{canCreateOffice&&<button type="button" className="flex h-9 w-full items-center gap-2 rounded-[5px] px-2 text-left text-[13px] font-medium text-[#33423b] hover:bg-[#f3f4f4]" onClick={()=>{setOpen(false);setError("");setCreateOpen(true);}}><Plus size={15}/>Ajouter un bureau</button>}{parcelFreight&&!networkConfigured&&<Link href="/app/settings?section=network" onClick={()=>setOpen(false)} className="flex h-9 items-center gap-2 rounded-[5px] px-2 text-[13px] font-medium text-[#33423b] hover:bg-[#f3f4f4]"><Network size={15}/>Configurer le réseau</Link>}{networkConfigured&&<Link href="/app/settings?section=network" onClick={()=>setOpen(false)} className="flex h-9 items-center gap-2 rounded-[5px] px-2 text-[13px] text-[#59636c] hover:bg-[#f3f4f4]"><Settings2 size={15}/>Réseau et équipe</Link>}{!parcelFreight&&<button type="button" className="flex h-9 w-full items-center gap-2 rounded-[5px] px-2 text-left text-[13px] text-[#59636c] hover:bg-[#f3f4f4]" onClick={()=>{setOpen(false);setError("");setCreateOpen(true);}}><Plus size={15}/>Créer une organisation</button>}</div></div>}
    {error&&<p className="mt-1 px-1 text-[11px] text-red-600">{error}</p>}
    <OperationDrawer open={createOpen} close={()=>{if(!creating)setCreateOpen(false);}} title={networkConfigured?"Ajouter un bureau":"Créer une organisation"} description={networkConfigured?"Créez un bureau du même réseau. Il conserve ses opérations, son équipe et son canal WhatsApp.":"Créez un espace séparé avec ses propres clients, dossiers, messages et réglages."} footer={<><OperationButton type="button" onClick={()=>setCreateOpen(false)} disabled={creating}>Annuler</OperationButton><OperationButton type="submit" form="create-workspace-form" variant="primary" disabled={creating||(!networkConfigured&&organizationName.trim().length<2)}>{creating?"Création…":networkConfigured?"Créer le bureau":"Créer"}</OperationButton></>}>
      <form id="create-workspace-form" onSubmit={handleCreate} className="grid gap-4">{networkConfigured?<><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-[13px] font-semibold text-[#414950]">Nom du bureau<input required name="organization_name" maxLength={120} autoFocus placeholder="Ex. LUZA Kinshasa" className={inputClass}/></label><label className="grid gap-2 text-[13px] font-semibold text-[#414950]">Code du bureau<input required name="office_code" pattern="[A-Za-z0-9_-]{2,30}" placeholder="KIN-01" className={inputClass}/></label></div><div className="grid gap-4 sm:grid-cols-2"><FormGeographyFields required countryCodeName="country_code" className={inputClass} fieldClassName="grid gap-2 text-[13px] font-semibold text-[#414950]"/><label className="grid gap-2 text-[13px] font-semibold text-[#414950]">Devise<select name="currency_code" className={inputClass} defaultValue="USD"><option>USD</option><option>EUR</option><option>CDF</option><option>AOA</option><option>CNY</option><option>XOF</option></select></label><label className="grid gap-2 text-[13px] font-semibold text-[#414950]">Téléphone<PhoneField name="phone" className={inputClass}/></label><label className="grid gap-2 text-[13px] font-semibold text-[#414950]">Email<input name="email" type="email" className={inputClass}/></label><label className="grid gap-2 text-[13px] font-semibold text-[#414950]">Adresse · ligne 1<input name="address_line_1" className={inputClass}/></label><label className="grid gap-2 text-[13px] font-semibold text-[#414950]">Adresse · ligne 2<input name="address_line_2" className={inputClass}/></label></div></>:<label htmlFor="organization-name" className="grid gap-2 text-[13px] font-semibold text-[#414950]">Nom de l’organisation<input id="organization-name" value={organizationName} onChange={event=>setOrganizationName(event.target.value)} maxLength={120} autoFocus placeholder="Ex. Slaivio France" className={inputClass}/></label>}{error&&<p className="text-[12px] text-red-600">{error}</p>}</form>
    </OperationDrawer>
  </div>;
}
