WORKFLOW_BY_INTENT = {
    "PRICING_REQUEST": "PRICING_ANSWER",
    "TRACKING_REQUEST": "TRACKING_LOOKUP",
    "SHIPMENT_CREATION": "CREATE_SHIPMENT_DRAFT",
    "SUPPLIER_DEPOSIT": "SUPPLIER_DEPOSIT_DRAFT",
    "PAYMENT_QUESTION": "PAYMENT_HELP",
    "COMPLAINT": "ESCALATION_REQUIRED",
    "HUMAN_AGENT_REQUEST": "ESCALATION_REQUIRED",
    "GENERAL_QUESTION": "NO_WORKFLOW",
    "UNKNOWN": "NO_WORKFLOW",
}


def get_workflow_type(intent: str):
    return WORKFLOW_BY_INTENT.get(intent, "NO_WORKFLOW")

