"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { MapPin } from "lucide-react";

import { OnboardingError, OnboardingFooter, OnboardingHeading, OnboardingLoading, OnboardingShell, onboardingInputClass, onboardingPrimaryButtonClass, onboardingSkipButtonClass } from "@/components/onboarding/OnboardingShell";
import { useOnboardingState } from "@/components/onboarding/use-onboarding-state";
import { completeOnboardingStep, skipOnboardingStep } from "@/services/onboarding-experience";
import { getOnboardingStatus } from "@/services/onboarding";
import { getPilotSettings, saveLocation } from "@/services/organization-admin";

type FormState={name:string;code:string;location_type:"OFFICE"|"WAREHOUSE"|"HUB"|"PICKUP_POINT";country:string;city:string;address:string;phone:string;whatsapp:string};
const empty:FormState={name:"",code:"",location_type:"OFFICE",country:"",city:"",address:"",phone:"",whatsapp:""};

export default function OperationsOnboardingPage(){
  const router=useRouter(); const {state,error:stateError,reload}=useOnboardingState();
  const [form,setForm]=useState(empty); const [businessType,setBusinessType]=useState<"VEHICLE_IMPORT"|"PARCEL_FREIGHT">("VEHICLE_IMPORT"); const [existing,setExisting]=useState<Array<{id:string;name:string;city:string;country:string;location_type:string}>>([]); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
  useEffect(()=>{Promise.all([getOnboardingStatus(),getPilotSettings()]).then(([onboarding,settings])=>{const type=onboarding.profile?.business_type||"VEHICLE_IMPORT";setBusinessType(type);setExisting(settings.locations);setForm(current=>({...current,name:settings.organization.organization_name||current.name,country:settings.organization.country||current.country,city:settings.organization.city||current.city,address:settings.organization.address||current.address,phone:settings.organization.phone||current.phone,location_type:type==="PARCEL_FREIGHT"?"WAREHOUSE":"OFFICE"}));}).catch(()=>setError("Les informations de l’agence ne peuvent pas être chargées."));},[]);
  const set=(key:keyof FormState,value:string)=>setForm(current=>({...current,[key]:value}));
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setError("");try{await saveLocation({workspace_id:null,name:form.name,code:form.code,location_type:form.location_type,country:form.country,city:form.city,address:form.address||null,phone:form.phone||null,whatsapp:form.whatsapp||null,email:null,manager_name:null,opening_hours:{},timezone:"UTC",services:[]});await completeOnboardingStep("OPERATIONS");router.push("/onboarding/whatsapp");}catch{setError("Le site principal n’a pas pu être enregistré. Vérifiez notamment son code.");setSaving(false);}}
  async function continueExisting(){setSaving(true);setError("");try{await completeOnboardingStep("OPERATIONS");router.push("/onboarding/whatsapp");}catch{setError("Impossible de continuer pour le moment.");setSaving(false);}}
  async function skip(){setSaving(true);setError("");try{await skipOnboardingStep("OPERATIONS");router.push("/onboarding/whatsapp");}catch{setError("Cette étape ne peut pas être reportée pour le moment.");setSaving(false);}}
  if(!state)return stateError?<OnboardingError message={stateError} retry={()=>void reload()}/>:<OnboardingLoading/>;
  const parcel=businessType==="PARCEL_FREIGHT";
  return <OnboardingShell state={state} currentStep="OPERATIONS"><OnboardingHeading eyebrow="Étape 2 sur 5" title={parcel?"Ajoutez votre premier site opérationnel":"Ajoutez le bureau principal de l’agence"} description={parcel?"Ce lieu servira à réceptionner les colis et à indiquer clairement les adresses de dépôt ou de retrait aux clients.":"Ce bureau permet d’identifier l’agence qui suit les dossiers et communique avec les clients."}/>
    {existing.length>0&&<section className="mb-8 rounded-[9px] bg-[#f5faf7] p-4"><p className="text-[13px] font-semibold text-[#276247]">Un site est déjà configuré</p>{existing.slice(0,2).map(item=><p key={item.id} className="mt-2 flex items-center gap-2 text-[13px] text-[#52635a]"><MapPin size={14}/>{item.name} · {item.city}, {item.country}</p>)}<button onClick={continueExisting} disabled={saving} className="mt-4 text-[13px] font-semibold text-[#148152] hover:underline">Conserver et continuer</button></section>}
    <form onSubmit={submit}><div className="grid gap-5 sm:grid-cols-2"><Field label={parcel?"Nom du dépôt ou entrepôt":"Nom du bureau"}><input required className={onboardingInputClass} value={form.name} onChange={e=>set("name",e.target.value)}/></Field><Field label="Code court" hint="Ex. BXL01"><input required pattern="[A-Za-z0-9_-]{2,30}" className={onboardingInputClass} value={form.code} onChange={e=>set("code",e.target.value.toUpperCase())}/></Field><Field label="Type de site"><select className={onboardingInputClass} value={form.location_type} onChange={e=>set("location_type",e.target.value)}>{parcel?<><option value="WAREHOUSE">Entrepôt</option><option value="HUB">Hub de transit</option><option value="PICKUP_POINT">Point de dépôt ou retrait</option></>:<><option value="OFFICE">Bureau d’agence</option><option value="HUB">Centre opérationnel</option></>}</select></Field><Field label="Pays"><input required className={onboardingInputClass} value={form.country} onChange={e=>set("country",e.target.value)}/></Field><Field label="Ville"><input required className={onboardingInputClass} value={form.city} onChange={e=>set("city",e.target.value)}/></Field><Field label={parcel?"Adresse de dépôt":"Adresse du bureau"}><input className={onboardingInputClass} value={form.address} onChange={e=>set("address",e.target.value)}/></Field><Field label="Téléphone du site"><input type="tel" className={onboardingInputClass} value={form.phone} onChange={e=>set("phone",e.target.value)}/></Field><Field label="WhatsApp du site"><input type="tel" className={onboardingInputClass} value={form.whatsapp} onChange={e=>set("whatsapp",e.target.value)}/></Field></div>{error&&<p role="alert" className="mt-6 rounded-[7px] bg-[#fff3f1] px-4 py-3 text-[13px] text-[#a33a32]">{error}</p>}<OnboardingFooter backHref="/onboarding/agency-profile"><button type="button" onClick={skip} disabled={saving} className={onboardingSkipButtonClass}>Passer pour l’instant</button><button disabled={saving} className={onboardingPrimaryButtonClass}>{saving?"Enregistrement…":"Enregistrer et continuer"}</button></OnboardingFooter></form>
  </OnboardingShell>;
}
function Field({label,hint,children}:{label:string;hint?:string;children:React.ReactNode}){return <label><span className="mb-2 flex items-center gap-2 text-[13px] font-medium text-[#344049]">{label}{hint&&<span className="text-[11px] font-normal text-[#8a949b]">{hint}</span>}</span>{children}</label>}
