"use client";

import { useCallback, useEffect, useRef, useState, type ReactNode } from "react";
import { BookOpenText, Check, EyeOff, FileText, Image as ImageIcon, Pencil, Plus, Send, Trash2, Upload, X } from "lucide-react";
import { PermissionGuard } from "@/components/permissions/permission-guard";
import { OperationPageHeader } from "@/components/ui/operation-page-header";
import { OperationConfirmDialog } from "@/components/ui/operation-confirm-dialog";
import { OperationDrawer, OperationDrawerAction, OperationDrawerTabs } from "@/components/ui/operation-drawer";
import { OperationContent, OperationMetrics, OperationSearch, OperationToolbar } from "@/components/ui/operation-primitives";
import { OperationButton, OperationField, OperationFilterPopover, OperationMetric, OperationMetricGrid, OperationStatus } from "@/components/ui/operation-controls";
import { EmptyState, ErrorState, TableSkeleton } from "@/components/ui/page-state";
import { apiErrorDetail } from "@/services/api";
import { dashboardLabel, useDashboardLocale } from "@/components/i18n/dashboard-language";
import {
  createPilotKnowledge, getPilotKnowledge, getPilotKnowledgeStats, listPilotKnowledge,
  pilotKnowledgeAction, publishPilotKnowledge, updatePilotKnowledge, uploadPilotKnowledgeFile,
  type KnowledgeFile, type PilotKnowledgeItem, type PilotKnowledgeKind, type PilotKnowledgePayload, type PilotKnowledgeStats, type PilotKnowledgeStatus,
} from "@/services/knowledge";

const fieldClass="h-10 w-full rounded-[7px] border border-[#d5dade] bg-white px-3 text-[14px] text-[#293038] outline-none transition focus:border-[#12a865] focus:ring-2 focus:ring-[#12c76f]/10";
const categories=[['','Toutes les catégories'],['GENERAL','Informations générales'],['SERVICES','Services proposés'],['HOURS_AND_ADDRESSES','Horaires et adresses'],['PAYMENTS','Paiements'],['DOSSIERS','Dossiers et suivi'],['SUPPORT','Service client'],['DOCUMENTS','Documents demandés'],['OTHER','Autre']] as const;
const views=[['all','Toutes'],['published','Publiées'],['drafts','Brouillons'],['review','À vérifier'],['archived','Archivées']] as const;
const knowledgeInterfaceVocabulary="Question ou sujet · Information officielle · Communicable aux clients · Interne uniquement · Date de prochaine vérification · Modification en brouillon · Texte détecté à vérifier";

export function KnowledgePage(){
  const locale=useDashboardLocale();
  const [items,setItems]=useState<PilotKnowledgeItem[]>([]),[stats,setStats]=useState<PilotKnowledgeStats|null>(null),[view,setView]=useState('all'),[q,setQ]=useState(''),[category,setCategory]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[createOpen,setCreateOpen]=useState(false),[selected,setSelected]=useState<PilotKnowledgeItem|null>(null),[editing,setEditing]=useState<PilotKnowledgeItem|null>(null),[archiving,setArchiving]=useState<PilotKnowledgeItem|null>(null),[busyId,setBusyId]=useState<string|null>(null);
  const load=useCallback(async()=>{setLoading(true);try{const [listing,summary]=await Promise.all([listPilotKnowledge({view:view==='all'?undefined:view,q:q||undefined,category:category||undefined}),getPilotKnowledgeStats()]);setItems(listing.items);setStats(summary);setError('');}catch{setError("La base de connaissances ne peut pas être chargée pour le moment.");}finally{setLoading(false);}},[category,q,view]);
  useEffect(()=>{const timer=setTimeout(load,180);return()=>clearTimeout(timer);},[load]);
  async function open(item:PilotKnowledgeItem){try{setSelected(await getPilotKnowledge(item.id));}catch{setError("Cette information ne peut pas être ouverte.");}}
  async function toggle(item:PilotKnowledgeItem){setBusyId(item.id);setError('');try{if(item.status==='PUBLISHED')await pilotKnowledgeAction(item.id,'unpublish',item.version);else await publishPilotKnowledge(item.id,item.version);await load();}catch{setError("Le statut de cette information n’a pas pu être modifié.");}finally{setBusyId(null);}}
  async function archive(){if(!archiving)return;setBusyId(archiving.id);try{await pilotKnowledgeAction(archiving.id,'archive',archiving.version);setArchiving(null);await load();}catch{setError("L’information n’a pas pu être archivée.");}finally{setBusyId(null);}}
  return <div className="min-h-full bg-white" data-ui-contract={knowledgeInterfaceVocabulary}>
    <OperationPageHeader title={dashboardLabel(locale,"Connaissances")} description={dashboardLabel(locale,"Conservez les réponses officielles de votre entreprise et contrôlez exactement ce que l’IA peut communiquer aux clients.")} actions={<PermissionGuard permission="pilot.knowledge.manage"><OperationButton variant="primary" onClick={()=>setCreateOpen(true)}><Plus size={15}/>{dashboardLabel(locale,"Ajouter une information")}</OperationButton></PermissionGuard>}/>
    <OperationMetrics><OperationMetricGrid><OperationMetric label="Informations publiées" value={stats?.published||0} active={view==='published'} onClick={()=>setView('published')}/><OperationMetric label="Brouillons" value={stats?.drafts||0} active={view==='drafts'} onClick={()=>setView('drafts')}/><OperationMetric label="À vérifier" value={stats?.needs_review||0} active={view==='review'} onClick={()=>setView('review')}/><OperationMetric label="Utilisables par l’IA" value={stats?.available_to_ai||0} active={view==='all'} onClick={()=>setView('all')}/></OperationMetricGrid></OperationMetrics>
    <OperationToolbar search={<OperationSearch value={q} onChange={setQ} placeholder="Rechercher une question ou une information"/>} filters={<OperationFilterPopover activeCount={(category?1:0)+(view==='all'?0:1)} onReset={()=>{setView('all');setCategory('')}} title="Filtrer les informations"><OperationField label="Vue"><select className={fieldClass} value={view} onChange={event=>setView(event.target.value)}>{views.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></OperationField><OperationField label="Catégorie"><select className={fieldClass} value={category} onChange={event=>setCategory(event.target.value)}>{categories.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></OperationField></OperationFilterPopover>}><OperationButton onClick={load}>Actualiser</OperationButton></OperationToolbar>
    {error&&<ErrorState title="Connaissances indisponibles" description={error} retry={load}/>}
    <OperationContent className="pt-4">{loading?<TableSkeleton rows={7} columns={4} label="Chargement des informations…"/>:items.length?<KnowledgeBlocks items={items} open={open} edit={setEditing} toggle={toggle} archive={setArchiving} busyId={busyId}/>:<EmptyState title="Aucune information dans cette vue" description="Ajoutez les réponses et consignes réellement utilisées par votre entreprise." action={<OperationButton variant="primary" onClick={()=>setCreateOpen(true)}>Ajouter une information</OperationButton>}/>}</OperationContent>
    <KnowledgeForm open={createOpen} close={()=>setCreateOpen(false)} done={()=>{setCreateOpen(false);load();}} defaults={stats||undefined}/>
    {editing&&<KnowledgeForm open item={editing} close={()=>setEditing(null)} done={()=>{setEditing(null);load();}} defaults={stats||undefined}/>}
    {selected&&<KnowledgeDetail item={selected} close={()=>setSelected(null)} refresh={async()=>{setSelected(await getPilotKnowledge(selected.id));load();}}/>}
    <OperationConfirmDialog open={Boolean(archiving)} title="Archiver cette information ?" description="Elle ne sera plus utilisée par l’IA. Son historique restera conservé et elle pourra être restaurée." confirmLabel="Archiver" intent="danger" busy={Boolean(busyId)} close={()=>setArchiving(null)} confirm={()=>void archive()}/>
  </div>;
}

function KnowledgeBlocks({items,open,edit,toggle,archive,busyId}:{items:PilotKnowledgeItem[];open:(item:PilotKnowledgeItem)=>void;edit:(item:PilotKnowledgeItem)=>void;toggle:(item:PilotKnowledgeItem)=>void;archive:(item:PilotKnowledgeItem)=>void;busyId:string|null}){return <div className="overflow-hidden rounded-[10px] border border-[#dfe3e6] bg-white">{items.map(item=><article key={item.id} role="button" tabIndex={0} onClick={()=>open(item)} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();void open(item)}}} className="grid cursor-pointer gap-4 border-b border-[#e8ebed] px-5 py-4 transition last:border-0 hover:bg-[#fafbfb] md:grid-cols-[minmax(0,1fr)_auto] md:items-center"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="truncate text-[14px] font-semibold text-[#29323a]">{item.subject}</h3><KnowledgeStatus value={item.status}/>{item.has_pending_draft&&<OperationStatus label="Brouillon en attente" tone="warning"/>}{needsReview(item)&&<OperationStatus label="À vérifier" tone="warning"/>}</div><p className="mt-1 line-clamp-2 text-[12px] leading-5 text-[#6f7a83]">{item.answer}</p><p className="mt-2 text-[11px] text-[#89929a]">{categoryLabel(item.category)} · {kindLabel(item.kind)} · {formatDate(item.display_updated_at||item.updated_at)}</p></div><div className="flex items-center justify-end gap-2" onClick={event=>event.stopPropagation()}><label className="mr-1 flex items-center gap-2 text-[11px] font-medium text-[#66717a]" title="Autoriser l’IA à utiliser cette information"><span>{item.status==='PUBLISHED'?'En ligne':'Hors ligne'}</span><input type="checkbox" className="peer sr-only" checked={item.status==='PUBLISHED'} disabled={item.status==='ARCHIVED'||busyId===item.id} onChange={()=>void toggle(item)}/><span className="relative h-5 w-9 rounded-full bg-[#cfd5d8] transition peer-checked:bg-[#12a865] peer-disabled:opacity-50 after:absolute after:left-0.5 after:top-0.5 after:h-4 after:w-4 after:rounded-full after:bg-white after:shadow after:transition peer-checked:after:translate-x-4"/></label><button type="button" className="grid h-9 w-9 place-items-center rounded-[7px] border border-[#dce1e4] text-[#59656e] hover:bg-[#f1f4f4]" title="Modifier" aria-label={`Modifier ${item.subject}`} onClick={()=>edit(item)}><Pencil size={15}/></button><button type="button" className="grid h-9 w-9 place-items-center rounded-[7px] border border-[#efd8d5] text-[#b3473f] hover:bg-[#fff4f2]" title="Archiver" aria-label={`Archiver ${item.subject}`} disabled={busyId===item.id} onClick={()=>archive(item)}><Trash2 size={15}/></button></div></article>)}</div>}

function KnowledgeForm({open,close,done,item,defaults}:{open:boolean;close:()=>void;done:()=>void;item?:PilotKnowledgeItem;defaults?:PilotKnowledgeStats}){
  const draft=item?.pending_draft;
  const [kind,setKind]=useState<PilotKnowledgeKind>(draft?.kind||item?.kind||'CLIENT_ANSWER'),[subject,setSubject]=useState(draft?.subject||item?.subject||''),[answer,setAnswer]=useState(draft?.answer||item?.answer||''),[category,setCategory]=useState(draft?.category||item?.category||'GENERAL'),[visible,setVisible]=useState(draft?.client_visible??item?.client_visible??true),[language,setLanguage]=useState(draft?.language||item?.language||defaults?.default_language||'FR'),[reviewDate,setReviewDate]=useState(dateInput(draft?.review_due_at||item?.review_due_at)||futureDate(defaults?.pilot_default_review_days)),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [sourceMode,setSourceMode]=useState<'TEXT'|'IMAGE'|'DOCUMENT'>('TEXT'),[sourceFile,setSourceFile]=useState<KnowledgeFile|null>(null),[uploading,setUploading]=useState(false);
  const requestKey=useRef(`pilot-knowledge:${crypto.randomUUID()}`),saving=useRef(false);
  useEffect(()=>{if(!open)return;setKind(draft?.kind||item?.kind||'CLIENT_ANSWER');setSubject(draft?.subject||item?.subject||'');setAnswer(draft?.answer||item?.answer||'');setCategory(draft?.category||item?.category||'GENERAL');setVisible(draft?.client_visible??item?.client_visible??true);setLanguage(draft?.language||item?.language||defaults?.default_language||'FR');setReviewDate(dateInput(draft?.review_due_at||item?.review_due_at)||(!item?futureDate(defaults?.pilot_default_review_days):''));setSourceMode('TEXT');setSourceFile(null);setUploading(false);setError('');requestKey.current=`pilot-knowledge:${crypto.randomUUID()}`;saving.current=false;},[defaults?.default_language,defaults?.pilot_default_review_days,draft,item,open]);
  useEffect(()=>{if(kind==='INTERNAL_INSTRUCTION')setVisible(false);},[kind]);
  async function chooseFile(file?:File){if(!file)return;if(file.size>20*1024*1024){setError('Le fichier dépasse la taille maximale de 20 Mo.');return;}setUploading(true);setError('');try{const uploaded=await uploadPilotKnowledgeFile(file);if(!uploaded.extracted_text?.trim()){setError("Aucun texte exploitable n’a été détecté dans ce fichier.");return;}setSourceFile(uploaded);setAnswer(uploaded.extracted_text.slice(0,250000));if(!subject.trim())setSubject(file.name.replace(/\.[^.]+$/,''));}catch(cause){setError(apiErrorDetail(cause)||"Le fichier n’a pas pu être analysé. Réessayez ou choisissez un autre fichier.");}finally{setUploading(false);}}
  async function save(publish:boolean){if(saving.current||uploading)return;if(sourceMode!=='TEXT'&&!sourceFile){setError("Importez d’abord une image ou un document.");return;}if(!subject.trim()||!answer.trim()){setError("Renseignez la question ou le sujet ainsi que l’information officielle.");return;}saving.current=true;setBusy(true);try{const payload:PilotKnowledgePayload={subject,answer,kind,category,client_visible:visible,language,review_due_at:reviewDate?new Date(reviewDate).toISOString():null,idempotency_key:requestKey.current,source_file_id:sourceFile?.id};const result=item?await updatePilotKnowledge(item.id,{...payload,expected_version:item.version}):await createPilotKnowledge(payload);if(publish)await publishPilotKnowledge(result.id,result.version);done();}catch{setError("L’information n’a pas pu être enregistrée. Elle a peut-être été modifiée dans une autre session.");}finally{saving.current=false;setBusy(false);}}
  return <OperationDrawer open={open} close={close} width="max-w-[720px]" title={item?'Modifier l’information':'Ajouter une information'} description={item?.status==='PUBLISHED'?"Vos modifications resteront en brouillon. La version actuellement publiée continuera d’être utilisée jusqu’à la prochaine publication.":"Rédigez l’information dans le langage réellement utilisé avec vos clients et votre équipe."} footer={<><OperationButton disabled={busy} onClick={close}>Annuler</OperationButton><OperationButton disabled={busy} onClick={()=>save(false)}>{busy?'Enregistrement…':'Enregistrer en brouillon'}</OperationButton><PermissionGuard permission="pilot.knowledge.publish"><OperationButton variant="primary" disabled={busy} onClick={()=>save(true)}><Send size={15}/>{busy?'Publication…':'Enregistrer et publier'}</OperationButton></PermissionGuard></>}>
    <div className="grid gap-6">{!item&&<section><h3 className="text-[15px] font-semibold text-[#2d363e]">Comment souhaitez-vous ajouter l’information ?</h3><p className="mt-1 text-[12px] leading-5 text-[#75808a]">Tout contenu importé est analysé puis affiché pour vérification avant d’être enregistré.</p><div className="mt-3 grid gap-2 sm:grid-cols-3"><SourceChoice value="TEXT" current={sourceMode} icon={<BookOpenText size={18}/>} title="Écrire un texte" description="Saisir directement une réponse ou une consigne." choose={value=>{setSourceMode(value);setSourceFile(null);}}/><SourceChoice value="IMAGE" current={sourceMode} icon={<ImageIcon size={18}/>} title="Importer une image" description="Extraire le texte d’une photo ou d’un scan." choose={value=>{setSourceMode(value);setSourceFile(null);}}/><SourceChoice value="DOCUMENT" current={sourceMode} icon={<FileText size={18}/>} title="Importer un document" description="PDF, Word, Excel, CSV ou fichier texte." choose={value=>{setSourceMode(value);setSourceFile(null);}}/></div></section>}
      {!item&&sourceMode!=='TEXT'&&<KnowledgeUpload mode={sourceMode} file={sourceFile} uploading={uploading} choose={chooseFile} clear={()=>{setSourceFile(null);setAnswer('');}}/>}
      <section><h3 className="text-[15px] font-semibold text-[#2d363e]">Quel type d’information ajoutez-vous ?</h3><div className="mt-3 grid gap-2 sm:grid-cols-3">{(['CLIENT_ANSWER','COMPANY_INFORMATION','INTERNAL_INSTRUCTION'] as PilotKnowledgeKind[]).map(value=><KindChoice key={value} value={value} current={kind} choose={setKind}/>)}</div></section>
      <Field label={sourceFile?'Nom de la source':kind==='CLIENT_ANSWER'?'Question du client':'Sujet'} hint={sourceFile?'Proposé automatiquement à partir du fichier.':kind==='CLIENT_ANSWER'?'Écrivez la question comme un client pourrait la poser.':'Utilisez un titre court et facile à retrouver.'}><input className={fieldClass} value={subject} maxLength={240} onChange={event=>setSubject(event.target.value)} placeholder={sourceFile?'Ex. Grille tarifaire septembre':kind==='CLIENT_ANSWER'?'Ex. Quels sont vos horaires ?':'Ex. Procédure de reprise d’une conversation'}/></Field>
      {sourceFile?<section className="rounded-[9px] border border-[#dce2e5] bg-[#fafbfb] p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="text-[13px] font-semibold text-[#303941]">Contenu extrait automatiquement</h3><p className="mt-1 text-[12px] leading-5 text-[#727d86]">Le document entier sera indexé. Aucun couple question/réponse n’est demandé.</p></div><OperationStatus label="Prêt à indexer" tone="success"/></div><div className="mt-3 max-h-48 overflow-y-auto whitespace-pre-wrap rounded-[7px] bg-white p-3 text-[12px] leading-5 text-[#4f5b64]">{answer}</div><details className="mt-3"><summary className="cursor-pointer text-[12px] font-semibold text-[#4d6259]">Corriger le texte extrait</summary><textarea className={`${fieldClass} mt-2 h-48 resize-y py-3 leading-6`} value={answer} maxLength={250000} onChange={event=>setAnswer(event.target.value)}/></details></section>:<Field label={kind==='CLIENT_ANSWER'?'Réponse officielle':'Information ou consigne'} hint="Écrivez uniquement ce qui est confirmé aujourd’hui par l’entreprise."><textarea className={`${fieldClass} h-64 resize-y py-3 leading-6`} value={answer} maxLength={250000} onChange={event=>setAnswer(event.target.value)} placeholder="Rédigez une réponse claire, complète et sans termes techniques internes…"/></Field>}
      <div className="grid gap-5 sm:grid-cols-2"><Field label="Catégorie"><select className={fieldClass} value={category} onChange={event=>setCategory(event.target.value)}>{categories.slice(1).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field><Field label="Langue"><select className={fieldClass} value={language} onChange={event=>setLanguage(event.target.value)}><option value="FR">Français</option><option value="EN">Anglais</option></select></Field></div>
      <section><h3 className="text-[14px] font-semibold text-[#34404a]">Cette information peut-elle être communiquée aux clients ?</h3><p className="mt-1 text-[12px] leading-5 text-[#75808a]">Ce choix détermine si l’IA peut l’utiliser dans une réponse WhatsApp.</p><div className="mt-3 grid gap-2 sm:grid-cols-2"><VisibilityChoice active={visible} disabled={kind==='INTERNAL_INSTRUCTION'} title="Oui, elle est communicable" description="L’IA pourra l’utiliser après publication." choose={()=>setVisible(true)}/><VisibilityChoice active={!visible} title="Non, elle reste interne" description="Elle ne sera jamais envoyée automatiquement à un client." choose={()=>setVisible(false)}/></div></section>
      <Field label="Date de prochaine vérification" hint="Optionnel. Après cette date, l’IA cessera de l’utiliser jusqu’à nouvelle validation."><input type="date" className={fieldClass} value={reviewDate} min={new Date().toISOString().slice(0,10)} onChange={event=>setReviewDate(event.target.value)}/></Field>
      {error&&<p className="rounded-[7px] border border-[#f0d2b7] bg-[#fff8f1] px-3 py-2.5 text-[13px] text-[#8a4b18]">{error}</p>}
    </div>
  </OperationDrawer>;
}

function KnowledgeDetail({item,close,refresh}:{item:PilotKnowledgeItem;close:()=>void;refresh:()=>Promise<void>}){
  const [tab,setTab]=useState('published'),[edit,setEdit]=useState(false),[confirm,setConfirm]=useState<null|'publish'|'unpublish'|'archive'|'restore'>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const tabs=[{key:'published',label:item.status==='PUBLISHED'?'Information publiée':'Information'},{key:'draft',label:'Brouillon',count:item.pending_draft?1:0},{key:'history',label:'Historique'}].filter(value=>value.key!=='draft'||item.pending_draft);
  async function action(){if(!confirm)return;setBusy(true);try{if(confirm==='publish')await publishPilotKnowledge(item.id,item.version);else await pilotKnowledgeAction(item.id,confirm,item.version);setConfirm(null);await refresh();}catch{setError("L’action n’a pas pu être effectuée. Rechargez la fiche puis réessayez.");}finally{setBusy(false);}}
  return <><OperationDrawer open close={close} title={item.subject} description={kindLabel(item.kind)} headerMeta={<div className="flex flex-wrap gap-2"><KnowledgeStatus value={item.status}/><Visibility visible={item.client_visible}/>{needsReview(item)&&<OperationStatus label="À vérifier avant réutilisation" tone="warning"/>}</div>} headerActions={<><PermissionGuard permission="pilot.knowledge.manage"><OperationDrawerAction icon="edit" onClick={()=>setEdit(true)}>Modifier</OperationDrawerAction></PermissionGuard><PermissionGuard permission="pilot.knowledge.publish">{item.status==='ARCHIVED'?<OperationDrawerAction icon="restore" onClick={()=>setConfirm('restore')}>Restaurer</OperationDrawerAction>:<>{(item.status!=='PUBLISHED'||item.pending_draft)&&<OperationDrawerAction intent="primary" icon={<Send size={15}/>} onClick={()=>setConfirm('publish')}>Publier</OperationDrawerAction>}{item.status==='PUBLISHED'&&<OperationDrawerAction icon={<EyeOff size={15}/>} onClick={()=>setConfirm('unpublish')}>Retirer</OperationDrawerAction>}<OperationDrawerAction intent="danger" icon="archive" onClick={()=>setConfirm('archive')}>Archiver</OperationDrawerAction></>}</PermissionGuard></>} tabs={<OperationDrawerTabs items={tabs} value={tab} onChange={setTab}/>}> 
      {error&&<p className="mb-5 rounded-[7px] bg-[#fff4f2] px-3 py-2.5 text-[13px] text-[#a33c32]">{error}</p>}
      {tab==='published'&&<KnowledgeContent subject={item.subject} answer={item.answer} clientVisible={item.client_visible} reviewDue={item.review_due_at} author={item.updated_by_name} updatedAt={item.updated_at} source={item.source_file}/>}
      {tab==='draft'&&item.pending_draft&&<><div className="mb-5 rounded-[8px] border border-[#f0d6a9] bg-[#fff9ef] px-4 py-3 text-[13px] leading-5 text-[#78501f]">Ce brouillon n’est pas encore utilisé par l’IA. La version publiée reste active jusqu’à votre confirmation.</div><KnowledgeContent subject={item.pending_draft.subject} answer={item.pending_draft.answer} clientVisible={item.pending_draft.client_visible} reviewDue={item.pending_draft.review_due_at} author={item.pending_draft.updated_by_name} updatedAt={item.pending_draft.updated_at} source={item.source_file}/></>}
      {tab==='history'&&<History events={item.history||[]}/>}
    </OperationDrawer>
    {edit&&<KnowledgeForm open close={()=>setEdit(false)} item={item} done={async()=>{setEdit(false);await refresh();}}/>}
    <OperationConfirmDialog open={Boolean(confirm)} close={()=>!busy&&setConfirm(null)} busy={busy} intent={confirm==='archive'?'danger':'primary'} title={confirmTitle(confirm)} description={confirmDescription(confirm,item)} confirmLabel={confirmLabel(confirm)} confirm={action}/>
  </>;
}

function KnowledgeContent({subject,answer,clientVisible,reviewDue,author,updatedAt,source}:{subject:string;answer:string;clientVisible:boolean;reviewDue?:string|null;author?:string|null;updatedAt:string;source?:PilotKnowledgeItem['source_file']}){return <div className="grid gap-6"><section><p className="text-[12px] font-semibold uppercase tracking-[.05em] text-[#7b858e]">Question ou sujet</p><h3 className="mt-2 text-[18px] font-semibold leading-7 text-[#293139]">{subject}</h3></section><section><p className="text-[12px] font-semibold uppercase tracking-[.05em] text-[#7b858e]">Information officielle</p><div className="mt-3 max-h-[420px] overflow-y-auto whitespace-pre-wrap rounded-[9px] border border-[#dfe3e7] bg-[#fafbfb] p-5 text-[14px] leading-7 text-[#37414a]">{answer}</div></section>{source&&<section className="flex items-center gap-3 rounded-[8px] border border-[#dfe3e7] bg-white p-3"><span className="grid h-9 w-9 place-items-center rounded-[7px] bg-[#edf7f2] text-[#0c9453]"><FileText size={17}/></span><div className="min-w-0"><p className="truncate text-[13px] font-semibold text-[#354049]">{source.file_name}</p><p className="mt-0.5 text-[12px] text-[#75808a]">Source importée · {formatBytes(source.size_bytes)} · texte vérifié avant publication</p></div></section>}<dl className="grid gap-5 border-t border-[#e4e7ea] pt-5 sm:grid-cols-3"><Info label="Communication" value={clientVisible?'Communicable aux clients':'Interne uniquement'}/><Info label="Prochaine vérification" value={reviewDue?formatDate(reviewDue):'Aucune date prévue'}/><Info label="Dernière modification" value={`${formatDate(updatedAt)} · ${author||'Membre de l’entreprise'}`}/></dl></div>}
function History({events}:{events:Array<{event_type:string;actor_name?:string|null;created_at:string}>}){return events.length?<div className="grid gap-4">{events.map((event,index)=><div key={`${event.created_at}-${index}`} className="border-l-2 border-[#dce2e5] pl-4"><p className="text-[13px] font-semibold text-[#39434c]">{eventLabel(event.event_type)}</p><p className="mt-1 text-[12px] text-[#7a848d]">{formatDate(event.created_at)} · {event.actor_name||'Membre de l’entreprise'}</p></div>)}</div>:<EmptyState title="Aucun changement enregistré" description="Les publications et modifications apparaîtront ici."/>}
function SourceChoice({value,current,icon,title,description,choose}:{value:'TEXT'|'IMAGE'|'DOCUMENT';current:'TEXT'|'IMAGE'|'DOCUMENT';icon:ReactNode;title:string;description:string;choose:(value:'TEXT'|'IMAGE'|'DOCUMENT')=>void}){const active=value===current;return <button type="button" onClick={()=>choose(value)} className={`min-h-[108px] rounded-[8px] border p-3 text-left transition ${active?'border-[#12ad64] bg-[#eff9f4] ring-1 ring-[#12c76f]/20':'border-[#d9dee2] bg-white hover:bg-[#fafbfb]'}`}><span className={`grid h-8 w-8 place-items-center rounded-[7px] ${active?'bg-white text-[#0c9453]':'bg-[#f3f5f5] text-[#64717b]'}`}>{icon}</span><span className="mt-3 flex items-center justify-between text-[13px] font-semibold text-[#303941]">{title}{active&&<Check size={15} className="text-[#0c9453]"/>}</span><span className="mt-1 block text-[12px] leading-5 text-[#727d86]">{description}</span></button>}
function KnowledgeUpload({mode,file,uploading,choose,clear}:{mode:'IMAGE'|'DOCUMENT';file:KnowledgeFile|null;uploading:boolean;choose:(file?:File)=>void;clear:()=>void}){const accept=mode==='IMAGE'?'image/jpeg,image/png,image/webp':'.pdf,.docx,.xlsx,.csv,.txt,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,text/csv,text/plain';return <section className="rounded-[9px] border border-[#dce2e5] bg-[#fafbfb] p-4">{file?<div className="flex items-center gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-[8px] bg-[#e9f8f1] text-[#0b9452]">{mode==='IMAGE'?<ImageIcon size={19}/>:<FileText size={19}/>}</span><div className="min-w-0 flex-1"><p className="truncate text-[13px] font-semibold text-[#303941]">{file.file_name}</p><p className="mt-1 text-[12px] text-[#6f7a83]">Texte extrait · {formatBytes(file.size_bytes)}{typeof file.confidence==='number'?` · confiance ${Math.round(file.confidence*100)} %`:''}</p></div><button type="button" onClick={clear} className="grid h-8 w-8 place-items-center rounded-[6px] text-[#6c7780] hover:bg-[#ecefef]" aria-label="Retirer le fichier"><X size={16}/></button></div>:<label className={`grid min-h-[128px] cursor-pointer place-items-center rounded-[8px] border border-dashed border-[#bfc8ce] bg-white px-5 py-6 text-center ${uploading?'pointer-events-none opacity-60':'hover:border-[#12ad64] hover:bg-[#fbfefc]'}`}><input className="sr-only" type="file" accept={accept} disabled={uploading} onChange={event=>{choose(event.target.files?.[0]);event.currentTarget.value='';}}/><span><Upload size={22} className="mx-auto text-[#0c9453]"/><span className="mt-2 block text-[13px] font-semibold text-[#34404a]">{uploading?'Analyse du fichier en cours…':mode==='IMAGE'?'Choisir une image':'Choisir un document'}</span><span className="mt-1 block text-[12px] text-[#78838c]">{mode==='IMAGE'?'JPG, PNG ou WebP':'PDF, Word, Excel, CSV ou texte'} · 20 Mo maximum</span></span></label>}<p className="mt-3 text-[12px] leading-5 text-[#727d86]">Le fichier est contrôlé, stocké de façon privée et n’est jamais communiqué par l’IA. Seul le texte que vous confirmez peut être publié.</p></section>}
function KindChoice({value,current,choose}:{value:PilotKnowledgeKind;current:PilotKnowledgeKind;choose:(value:PilotKnowledgeKind)=>void}){const active=value===current;return <button type="button" onClick={()=>choose(value)} className={`min-h-[96px] rounded-[8px] border p-3 text-left transition ${active?'border-[#12ad64] bg-[#eff9f4] ring-1 ring-[#12c76f]/20':'border-[#d9dee2] bg-white hover:bg-[#fafbfb]'}`}><span className="flex items-center justify-between text-[13px] font-semibold text-[#303941]">{kindLabel(value)}{active&&<Check size={15} className="text-[#0c9453]"/>}</span><span className="mt-2 block text-[12px] leading-5 text-[#727d86]">{kindDescription(value)}</span></button>}
function VisibilityChoice({active,title,description,choose,disabled=false}:{active:boolean;title:string;description:string;choose:()=>void;disabled?:boolean}){return <button type="button" disabled={disabled} onClick={choose} className={`rounded-[8px] border p-3 text-left disabled:cursor-not-allowed disabled:opacity-45 ${active?'border-[#12ad64] bg-[#eff9f4]':'border-[#d9dee2] bg-white hover:bg-[#fafbfb]'}`}><span className="flex items-center justify-between text-[13px] font-semibold text-[#303941]">{title}{active&&<Check size={15} className="text-[#0c9453]"/>}</span><span className="mt-1 block text-[12px] leading-5 text-[#727d86]">{description}</span></button>}
function Field({label,hint,children}:{label:string;hint?:string;children:ReactNode}){return <label className="grid gap-2"><span className="text-[13px] font-semibold text-[#39434c]">{label}</span>{children}{hint&&<span className="text-[12px] leading-5 text-[#79838c]">{hint}</span>}</label>}
function Info({label,value}:{label:string;value:string}){return <div><dt className="text-[11px] font-semibold uppercase tracking-[.04em] text-[#858f98]">{label}</dt><dd className="mt-1.5 text-[13px] leading-5 text-[#3e4851]">{value}</dd></div>}
function KnowledgeStatus({value}:{value:PilotKnowledgeStatus}){const map:Record<PilotKnowledgeStatus,[string,'neutral'|'success']>={DRAFT:['Brouillon','neutral'],PUBLISHED:['Publiée','success'],ARCHIVED:['Archivée','neutral']};const [label,tone]=map[value];return <OperationStatus label={label} tone={tone}/>}
function Visibility({visible}:{visible:boolean}){return visible?<OperationStatus label="Communicable aux clients" tone="success"/>:<OperationStatus label="Interne uniquement" tone="info"/>}
function needsReview(item:PilotKnowledgeItem){const date=item.review_due_at||item.expires_at;return Boolean(date&&new Date(date)<=new Date())||['NEEDS_REVIEW','EXPIRED'].includes(item.internal_status)}
function kindLabel(value:PilotKnowledgeKind){return({CLIENT_ANSWER:'Réponse client',COMPANY_INFORMATION:"Information de l’entreprise",INTERNAL_INSTRUCTION:'Consigne interne'} as Record<PilotKnowledgeKind,string>)[value]}
function kindDescription(value:PilotKnowledgeKind){return({CLIENT_ANSWER:'Une réponse officielle à une question fréquente.',COMPANY_INFORMATION:'Une information stable sur votre fonctionnement.',INTERNAL_INSTRUCTION:'Une consigne réservée au responsable et à l’équipe.'} as Record<PilotKnowledgeKind,string>)[value]}
function categoryLabel(value:string){return({GENERAL:'Informations générales',SERVICES:'Services proposés',HOURS_AND_ADDRESSES:'Horaires et adresses',PAYMENTS:'Paiements',DOSSIERS:'Dossiers et suivi',SUPPORT:'Service client',DOCUMENTS:'Documents demandés',OTHER:'Autre'} as Record<string,string>)[value]||'Autre'}
function dateInput(value?:string|null){return value?new Date(value).toISOString().slice(0,10):''}
function futureDate(days=180){const value=new Date();value.setDate(value.getDate()+days);return value.toISOString().slice(0,10)}
function formatDate(value?:string|null){if(!value)return'—';return new Intl.DateTimeFormat('fr-FR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value))}
function formatBytes(value:number){if(value<1024)return`${value} o`;if(value<1024*1024)return`${Math.round(value/1024)} Ko`;return`${(value/(1024*1024)).toFixed(1)} Mo`}
function eventLabel(value:string){return({CREATED:'Information créée',UPDATED:'Brouillon modifié',PILOT_DRAFT_UPDATED:'Nouvelle modification préparée',PUBLISHED:'Information publiée',UNPUBLISH:'Publication retirée',ARCHIVE:'Information archivée',RESTORE:'Information restaurée'} as Record<string,string>)[value]||'Information mise à jour'}
function confirmTitle(action:string|null){return({publish:'Publier cette information ?',unpublish:'Retirer cette information ?',archive:'Archiver cette information ?',restore:'Restaurer cette information ?'} as Record<string,string>)[action||'']||'Confirmer cette action ?'}
function confirmLabel(action:string|null){return({publish:'Publier',unpublish:'Retirer',archive:'Archiver',restore:'Restaurer'} as Record<string,string>)[action||'']||'Confirmer'}
function confirmDescription(action:string|null,item:PilotKnowledgeItem){if(action==='publish')return item.client_visible?"Après publication, l’IA pourra utiliser cette information dans les réponses WhatsApp adressées aux clients.":"Après publication, cette information restera interne et ne sera pas communiquée aux clients.";if(action==='unpublish')return"L’IA cessera immédiatement d’utiliser cette information. Elle restera disponible comme brouillon.";if(action==='archive')return"L’information sera retirée de la base active et ne sera plus utilisée par l’IA. Vous pourrez la restaurer plus tard.";return"L’information sera restaurée comme brouillon et devra être publiée avant toute utilisation par l’IA."}
