"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Bot, Check, MessageSquareText, Pause } from "lucide-react";

import { OnboardingError, OnboardingFooter, OnboardingHeading, OnboardingLoading, OnboardingShell, onboardingInputClass, onboardingPrimaryButtonClass, onboardingSkipButtonClass } from "@/components/onboarding/OnboardingShell";
import { useOnboardingState } from "@/components/onboarding/use-onboarding-state";
import { completeOnboardingStep, skipOnboardingStep } from "@/services/onboarding-experience";
import { createPilotKnowledge, getPilotKnowledgeStats, publishPilotKnowledge } from "@/services/knowledge";
import { getInboxAISettings, updateInboxAIMode, type InboxAIMode } from "@/services/inbox";

export default function AiKnowledgeOnboardingPage(){
  const router=useRouter(); const {state,error:stateError,reload}=useOnboardingState();
  const [mode,setMode]=useState<InboxAIMode>("SUGGESTION_ONLY"); const [published,setPublished]=useState(0); const [subject,setSubject]=useState(""); const [answer,setAnswer]=useState(""); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
  useEffect(()=>{Promise.all([getInboxAISettings(),getPilotKnowledgeStats()]).then(([settings,stats])=>{setMode(settings.pilot_response_mode);setPublished(stats.published);}).catch(()=>setError("Les réglages de l’IA ne peuvent pas être chargés."));},[]);
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setError("");try{if(mode==="CONTROLLED_AUTO"&&!published&&(!subject.trim()||!answer.trim())){setError("Ajoutez au moins une réponse fiable avant d’activer les réponses automatiques.");setSaving(false);return;}if(subject.trim()&&answer.trim()){const item=await createPilotKnowledge({subject:subject.trim(),answer:answer.trim(),kind:"CLIENT_ANSWER",category:"FAQ",client_visible:true,language:"FR",idempotency_key:`onboarding:${crypto.randomUUID()}`});await publishPilotKnowledge(item.id,item.version);}await updateInboxAIMode(mode);await completeOnboardingStep("AI_KNOWLEDGE");router.push("/onboarding/review");}catch{setError("La configuration de l’IA n’a pas pu être enregistrée.");setSaving(false);}}
  async function skip(){setSaving(true);setError("");try{await skipOnboardingStep("AI_KNOWLEDGE");router.push("/onboarding/review");}catch{setError("Cette étape ne peut pas être reportée pour le moment.");setSaving(false);}}
  if(!state)return stateError?<OnboardingError message={stateError} retry={()=>void reload()}/>:<OnboardingLoading/>;
  const parcel=state.business_type==="PARCEL_FREIGHT";
  return <OnboardingShell state={state} currentStep="AI_KNOWLEDGE"><form onSubmit={submit}><OnboardingHeading eyebrow="Étape 4 sur 5" title={parcel?"Préparez les réponses sur vos colis et départs":"Préparez les réponses sur vos dossiers véhicules"} description="Choisissez le niveau d’automatisation. L’IA utilisera uniquement les informations publiées par votre agence et les données opérationnelles du client."/>
    <section><h2 className="text-[14px] font-semibold">Comment souhaitez-vous commencer ?</h2><div className="mt-3 grid gap-3 sm:grid-cols-3"><ModeCard selected={mode==="SUGGESTION_ONLY"} icon={<MessageSquareText size={19}/>} title="Suggestions" description="L’IA prépare, un membre vérifie et envoie." onClick={()=>setMode("SUGGESTION_ONLY")}/><ModeCard selected={mode==="CONTROLLED_AUTO"} icon={<Bot size={19}/>} title="Mode automatique" description="SLAIVIO répond directement 24 h/24 si la réponse publiée est suffisamment fiable." onClick={()=>setMode("CONTROLLED_AUTO")}/><ModeCard selected={mode==="PAUSED"} icon={<Pause size={19}/>} title="En pause" description="La messagerie reste manuelle." onClick={()=>setMode("PAUSED")}/></div></section>
    <section className="mt-9 rounded-[10px] bg-[#f8f9fa] p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="text-[14px] font-semibold">Ajoutez une première réponse fiable</h2><p className="mt-1 text-[12px] leading-5 text-[#727d85]">{parcel?"Exemple : adresse de dépôt, tarifs, jours de départ, délais ou modalités de paiement.":"Exemple : documents requis, étapes d’un dossier, délais de transport ou modalités de paiement."}</p></div>{published>0&&<span className="inline-flex shrink-0 items-center gap-1.5 rounded-full bg-[#e6f6ee] px-2.5 py-1 text-[11px] font-semibold text-[#17764d]"><Check size={12}/>{published} publiée{published>1?"s":""}</span>}</div><div className="mt-5 grid gap-4"><label><span className="mb-2 block text-[13px] font-medium">Question ou sujet</span><input className={onboardingInputClass} value={subject} onChange={e=>setSubject(e.target.value)} placeholder={parcel?"Ex. Quand part le prochain envoi vers Kinshasa ?":"Ex. Quels documents faut-il pour ouvrir un dossier ?"}/></label><label><span className="mb-2 block text-[13px] font-medium">Réponse validée par l’agence</span><textarea className={`${onboardingInputClass} min-h-[110px] resize-y py-3`} value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Indiquez la réponse exacte qui peut être communiquée au client."/></label></div></section>
    {error&&<p role="alert" className="mt-6 rounded-[7px] bg-[#fff3f1] px-4 py-3 text-[13px] text-[#a33a32]">{error}</p>}<OnboardingFooter backHref="/onboarding/whatsapp"><button type="button" onClick={skip} disabled={saving} className={onboardingSkipButtonClass}>Configurer plus tard</button><button disabled={saving} className={onboardingPrimaryButtonClass}>{saving?"Enregistrement…":"Enregistrer et vérifier"}</button></OnboardingFooter>
  </form></OnboardingShell>;
}
function ModeCard({selected,icon,title,description,onClick}:{selected:boolean;icon:React.ReactNode;title:string;description:string;onClick:()=>void}){return <button type="button" role="radio" aria-checked={selected} onClick={onClick} className={`min-h-[130px] rounded-[9px] border p-4 text-left transition ${selected?"border-[#6257e6] bg-[#f7f6ff] ring-1 ring-[#6257e6]":"border-[#dce1e4] hover:border-[#b9c0c5]"}`}><span className={`grid h-9 w-9 place-items-center rounded-[8px] ${selected?"bg-[#e9e7ff] text-[#5045d6]":"bg-[#f2f4f4] text-[#6e7880]"}`}>{icon}</span><strong className="mt-3 block text-[13px]">{title}</strong><span className="mt-1 block text-[11px] leading-4 text-[#707b84]">{description}</span></button>}
